### PR TITLE
common: Add a DECAROTOR type

### PR DESCRIPTION
**Pull request by muramura**
I would add a 10-rotor helicopter with ArduPilot.
I have added a type for this.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@muramura This has conflicts because MAV_TYPE was removed from common.xml. We now just have it in minimal.xml and include minimal.xml into common.xml.

Can you please rebase to fix the conflict.

Otherwise sounds good to me - @auturgy @julianoes any comment (this is just addition of a deca-rotor type (we already have a **do**decorator, but this one is new).

**Comment by muramura** [comment]
@hamishwillee san.   I put the common.xml back in.
I had assigned 34 in common.xml MAV_TYPE in common.xml.
I assigned 35 to DECAROTOR.

**Comment by hamishwillee** [comment]
Hi @muramura 

Thanks. Unfortunately there still appears to be some conflict with minimal and it won't let me rebase. Can you rebase. Please use whatever the next free id is for the MAV_TYPE.

**Comment by muramura** [comment]
I've included minimal.xml in common.xml.
I was able to verify that mavgenerate.py was successful.

Screenshot from 2020-09-19 15-40-51

**Comment by muramura** [comment]
I PR'd again in #1483.

**Pull request closed without merging**
