### PR TITLE
Add component ID for a TUNNEL node

### PR DESCRIPTION
**Pull request by olliw42**
adds a default component ID for a tunnel communication partner node.

For the rational pl see https://github.com/mavlink/mavlink/issues/1225#issuecomment-529074833.

### CODE REVIEW

**Comment by hamishwillee** [comment]
This makes sense to me. Will we ever need more than one?

**Comment by olliw42** [comment]
> Will we ever need more than one?

very good question

maybe, potentially yes, why not.

I had given it some thought before, my conclusion in #1225 was that IMHO one default component ID would be totally sufficient, like with the bridge IDs. 

I mean, it's not like that there are not plenty of IDs available for use, these IDs here are just the suggested default IDs, to simplify configuration work. If more than one is needed one can do it, and some level of configuration is then needed anyhow.

Note also that such a default tunnel ID is needed only for "stand-alone tunnel nodes". Many nodes which may use the tunnel message might have however already an ID, e.g. the gimbal does have a gimbal ID.

So, I concluded, one might be sufficient. However, I have to clearly say that it of course can happen that at some point in future one finds that one isn't sufficient ... there are too many unknown variables for me to predict.

I'm sorry that I don't have a clear answer, and just can share my thoughts.

**Comment by hamishwillee** [comment]
Works for me. @auturgy Any thoughts?

**Comment by olliw42** [comment]
I think this are the sort of "fears" the devs had from day one with the tunnel message. And I can't really argue against it, it's a valid point, there is of course a risk of misuse of this message. 

My main arguments were that (1) if folks misuse it in their own (non-public) implementation it doesn't harm but may give them opportunities, (2) I doubt it would really reduce the efforts to standardize (I mean, those not interested to help to standardize wouldn't be helping anyway), and (3) it has also good use cases, for which it in fact would be difficult to establish a meaning full standard.

I hope/believe that with my first application of this message for MAVLink conform pass-through configuration of mounted components I have presented a good example.

> For instance, if using this for a gimbal, whilst the gimbal “speaks mavlink”, it isn’t a mavlink gimbal and would still require a bespoke driver.

the STorM32 has become quite MAVLink-ish recently, so I guess it's fair to call it a mavlink gimbal, yet I'm happy - and I blieve many users would be too - that one now can do this in a fully MAVLink conform way: https://youtu.be/FRyZ7VZ5lvY

a "bespoke driver" is only needed in the GUI, but that's I think fine since this doesn't affect any other party in the MAVLink game.

**Comment by auturgy** [comment]
Understood: I’m not blocking this, just making sure that we document consideration of the broader context.

Thanks for your efforts!

**Comment by olliw42** [comment]
THX

in case you haven't seen, hamishwillee already did a great effort in documentation: https://github.com/mavlink/mavlink-devguide/pull/207. 
In https://github.com/mavlink/mavlink/issues/1225#issuecomment-529794194 he pointed out that this docu is a draft not submitted soon to get a deeper review. Maybe a good place to ensure that the docu gives the proper broader context.

**Comment by hamishwillee** [comment]
@auturgy I would appreciate your https://github.com/mavlink/mavlink-devguide/pull/207
If only to say "Yes/No, that is not a strong enough explanation of when this should/should not be used."
I have pitched this as losing the benefits of MAVLink, but suitable for cases where MAVLink is purely a transport.

**Comment by hamishwillee** [comment]
Dev call. chatted about this, and the general thought was that a close analogy is a router - you need this to provide heartbeat for your tunnel node, when no other component makes sense. Correct?

**Comment by olliw42** [comment]
I don't understand the sentence

in the demonstrated application, the GUI needs a component ID to
* allow the GUI emit a heartbeat, which is needed to enable routing (at least in AP it is such, that it forwards messages only to links where it has seen a heartbeat)
* set the the target fields properly, to avoid broadcasting

**Comment by hamishwillee** [comment]
Thanks! Merged.

**Comment by olliw42** [comment]
THX!

**Pull request merged**
