### PR TITLE
CMake: Using find_program to find mavgen(.py)

### PR DESCRIPTION
**Pull request by thopiekar**
If neither mavgen nor mavgen.py have been found as executables in $PATH, then we will fallback to the hardcoded location (submodule).

Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com>

### CODE REVIEW

**Comment by hamishwillee** [comment]
@julianoes This changes cmake file from always taking the version in the current submodule to preferentially taking a version it finds on the system path. 
I don't know if that is desirable or not, or if the cmake changes are correct - can you please review?

**Comment by thopiekar** [comment]
Well, the pro is that you don't need to mess with submodules. Looking around the repositories here (other projects included), I noticed that you love to use submodules.
That makes sense if you are using Makefiles, but as you are using CMake, I would recommend to make use of it's "ExternalProject" functionalities.

I'm perfectly fine, if we add an if() around this section. I just managed to build and package pymavlink separately and it is installing scripts into /usr/bin/, so I want to make use of these.

**Comment by hamishwillee** [comment]
@thopiekar Thanks for the explanation. All sounds reasonable to me, but I'm deferring to @julianoes who will have a much more educated view :-)

**Comment by julianoes** [comment]
@thopiekar I think that an option to enable this would be good, so `-DUSE_SYSTEM_PYMAVLINK=ON`.

**Comment by hamishwillee** [comment]
This went stale - @thopiekar Are you planning on making the [change suggested](https://github.com/mavlink/mavlink/pull/1485#issuecomment-698718752) or should I close this?

**Comment by thopiekar** [comment]
Hello @hamishwillee !
Thank you for coming back on this! 

I lost this PR on my desk. I'll continue on this and it should be ready at the end of the week at the latest. 😉

**Comment by thopiekar** [comment]
Ok, correcting myself. Just found time and finished it before it forget about it again.

**Comment by hamishwillee** [comment]
:-) Thanks very much!
@julianoes You happy with this?

**Review by julianoes — APPROVED** [review]

**Pull request merged**
