### PR TITLE
pymavlink submodule update

### PR DESCRIPTION
**Pull request by amilcarlucas**
This merges the commit made by @LorenzMeier

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar @julianoes Can we get this merged?

**Comment by julianoes** [comment]
@hamishwillee I don't see any change in this PR? What happened?

**Comment by amilcarlucas** [comment]
mavlink/mavlink pymavlink submodule was pointing to a branch on mavlink/pymavlink
That pymavlink branch got merged to master.
This PR makes mavlink/mavlink pymavlink submodule point to a master on mavlink/pymavlink

And .... I made the mistake of already deleting the mavlink/pymavlink that mavlink currently points to.
I have unfortunately the habit of deleing branches once they get merged to master :(

**Comment by julianoes** [comment]
No worries, so what do we have to do now? 😄
I like when branches get deleted and cleaned up...

**Comment by amilcarlucas** [comment]
Just merge this one!! ;)

**Comment by julianoes** [comment]
Ok, but it now says out-of-date.

**Comment by amilcarlucas** [comment]
OK, I rebased it again ... @julianoes please merge it before @LorenzMeier  breaks it again

**Comment by julianoes** [comment]
Thx @amilcarlucas

**Pull request merged**
