### PR TITLE
csAirLink: correct enumeration name

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by davidbuzz** [comment]
approved, xml typo by original author

**Comment by hamishwillee** [comment]
Thank you. FYI @main2stels, this fixes build bugs introduced by your PR  #2065

**Review by hamishwillee — APPROVED** [review]
Thanks @peterbarker and @davidbuzz - much appreciated.

**Comment by davidbuzz** [comment]
@hamishwillee  - next time maybe don't merge a PR where the actions are failing..?  :-)  https://github.com/mavlink/mavlink/pull/2065

**Comment by davidbuzz** [comment]
any volunteers to open an identical PR at https://github.com/ardupilot/mavlink ?

**Comment by main2stels** [comment]
@peterbarker , thank you. Apparently I have a local problem, as there was a successful build on my computer.

**Comment by hamishwillee** [comment]
@davidbuzz Fair. I saw lots of green but clearly didn't look carefully enough.

**Pull request merged**
