### PR TITLE
Added AVSS custom commands and messages

### PR DESCRIPTION
**Pull request by Thomas-Li-AVSS**
AVSS is a Canadian aerospace company commercializing safety technologies for Urban Air Mobility. AVSS is first commercially available products are parachute recovery systems for commercial drones. 
We will use the MAVLink protocol as the interface protocol for all our products. So we apply for the following message ID range and command ID range: MAVLink messenger ID range: 60050 - 60099, MAVLink command ID range: 60050 - 60099.
We have added the AVSSUAS.xml file to define our commands and messages.

AVSS contact info:
company URL: https://www.avss.co 
email contact: josh.boudreau@avss.co       thomas.li@avss.co

### CODE REVIEW

**Comment by hamishwillee** [comment]
Sorry for the delay in responding.

As these are explicitly custom/out of standard messages, and because you're not an autopilot but more an external peripheral, the right place would be for this would probably be an external dialect: https://github.com/mavlink/mavlink/tree/master/external/dialects

This is a new folder we put in place for MAVLink users who don't want to be part of the standard (or at least yet) but want to avoid XML clashes with the standard ids. If you're operating in a closed system then you don't need to be part of MAVLink at all.

What we'd dearly like though is to avoid custom messages and instead work with you towards a message set that all vendors of similar systems can use. At that point support for your system is more likely to be added to popular GCSes and integrated flight stacks.

Would be great to discuss in person on the [dev call](https://mavlink.io/en/about/support.html#dev_call).

**Comment by hamishwillee** [comment]
FYI There is a CI format issue. On linux you can fix this from the root of the mavlink repo by running `./scripts/test.sh format`

**Comment by Thomas-Li-AVSS** [comment]
> FYI There is a CI format issue. On linux you can fix this from the root of the mavlink repo by running `./scripts/test.sh format`

Ok, Thank you for reminding me. I have format it and move it to external dialects.

**Comment by hamishwillee** [comment]
@julianoes @peterbarker This adds new external dialect AVSSUAS.xml. This passes validation locally when I build on ubuntu but is failing in the tests. Any ideas on how to debug?

**Comment by peterbarker** [comment]
Message range in the XML and in the initial comment here different.  I guess that got discussed, but for future reference I'd like to know the reasoning (save time in the future...)

**Comment by peterbarker** [comment]
The CI failure is pretty clear:
```
2021-07-15T06:31:03.5353321Z ERROR: /home/runner/work/mavlink/mavlink/external/dialects/AVSSUAS.xml:87:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'param', attribute 'units': [facet 'enumeration'] The value 'mv' is not an element of the set {'s', 'ds', 'cs', 'ms', 'us', 'Hz', 'MHz', 'km', 'dam', 'm', 'm/s', 'm/s/s', 'm/s*5', 'dm', 'dm/s', 'cm', 'cm^2', 'cm/s', 'mm', 'mm/s', 'mm/h', 'K', 'degC', 'cdegC', 'rad', 'rad/s', 'mrad/s', 'deg', 'deg/2', 'deg/s', 'cdeg', 'cdeg/s', 'degE5', 'degE7', 'rpm', 'V', 'cV', 'mV', 'A', 'cA', 'mA', 'mAh', 'mT', 'gauss', 'mgauss', 'hJ', 'W', 'mG', 'g', 'kg', 'Pa', 'hPa', 'kPa', 'mbar', '%', 'd%', 'c%', 'dB', 'dBm', 'KiB', 'KiB/s', 'MiB', 'MiB/s', 'bytes', 'bytes/s', 'bits/s', 'pix', 'dpix', 'g/min', 'cm^3/min', 'cm^3'}.
```

It's a case issue = `mv` vs `mV`.

@hamishwillee how were you attempting to run the tests that you couldn't repro?

**Comment by Thomas-Li-AVSS** [comment]
> Message range in the XML and in the initial comment here different. I guess that got discussed, but for future reference I'd like to know the reasoning (save time in the future...)

According to hamishwillee's suggestion, our .XML is an external dialect. So we follow the message ID range definition of external dialect to update the ID range.

**Comment by Thomas-Li-AVSS** [comment]
> The CI failure is pretty clear:
> 
> ```
> 2021-07-15T06:31:03.5353321Z ERROR: /home/runner/work/mavlink/mavlink/external/dialects/AVSSUAS.xml:87:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'param', attribute 'units': [facet 'enumeration'] The value 'mv' is not an element of the set {'s', 'ds', 'cs', 'ms', 'us', 'Hz', 'MHz', 'km', 'dam', 'm', 'm/s', 'm/s/s', 'm/s*5', 'dm', 'dm/s', 'cm', 'cm^2', 'cm/s', 'mm', 'mm/s', 'mm/h', 'K', 'degC', 'cdegC', 'rad', 'rad/s', 'mrad/s', 'deg', 'deg/2', 'deg/s', 'cdeg', 'cdeg/s', 'degE5', 'degE7', 'rpm', 'V', 'cV', 'mV', 'A', 'cA', 'mA', 'mAh', 'mT', 'gauss', 'mgauss', 'hJ', 'W', 'mG', 'g', 'kg', 'Pa', 'hPa', 'kPa', 'mbar', '%', 'd%', 'c%', 'dB', 'dBm', 'KiB', 'KiB/s', 'MiB', 'MiB/s', 'bytes', 'bytes/s', 'bits/s', 'pix', 'dpix', 'g/min', 'cm^3/min', 'cm^3'}.
> ```
> 
> It's a case issue = `mv` vs `mV`.
> 
> @hamishwillee how were you attempting to run the tests that you couldn't repro?

Thank you. 
I have fixed it. Please test it again.

**Comment by hamishwillee** [comment]
@peterbarker 
1. I was looking at the [end of the log](https://github.com/mavlink/mavlink/runs/3073906584?check_suite_focus=true#step:5:981). Should have searched for "ERROR" sorry. 
2. I was simply running a normal build on all.xml with validation enabled. For some reason it told me "validation passed OK" on this file. I'll have to investigate why this passed locally.
3. "Message range in the XML and in the initial comment here different. I guess that got discussed, but for future reference I'd like to know the reasoning (save time in the future...)" - fair enough, as stated above, the dialect moved "type" so the range had to change. Appreciate it is annoying, but also very easy to forget to update the original post on these things.

**Comment by hamishwillee** [comment]
@Thomas-Li-AVSS I'm merging now - thanks for your patience.

Once again, I recommend that you come to the call and/or propose generic messages. It is unlikely we'd accept this set into the standard as-is, so if you ever need to be compatible with common flight stacks/GCS you'll end up doing rework.

**Comment by Thomas-Li-AVSS** [comment]
> @Thomas-Li-AVSS I'm merging now - thanks for your patience.
> 
> Once again, I recommend that you come to the call and/or propose generic messages. It is unlikely we'd accept this set into the standard as-is, so if you ever need to be compatible with common flight stacks/GCS you'll end up doing rework.
> 
> PS Subsequent updates should just need to pass the CI tests if made by you. We don't validate the sanity of external dialects, just that they don't clash/pass tests.

@hamishwillee Sorry for the delay. We just saw this. We will follow up with your request.

**Pull request merged**
