### PR TITLE
Px4 modes

### PR DESCRIPTION
**Pull request by squilter**
adds support for px4 modes to pymavlink. It seems to work, but I would appreciate it if @LorenzMeier could check this out anyway.

This should allow dronekit-python and mavproxy to set and read modes on px4.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good to me. @tridge Any comments?

**Comment by MikaelFerland** [comment]
Nice works, thank you @squilter

**Comment by nacho-carnicero** [comment]
Looks great, thanks! Just a comment: drone kit-python uses ```mode_mapping_bynumber```, ```mode_mapping``` and ```mode_mapping_byname```for getting/setting the modes. Perhaps it could be a nice adding to integrate in this PR a modification of these functions for handling the PX4 modes.

**Comment by LorenzMeier** [comment]
@squilter Could you add these extensions?

**Comment by squilter** [comment]
Sure, but it would be mapping a `tuple` to a name (and vice versa). Is that going to break something?

**Comment by peterbarker** [comment]
@LorenzMeier @squilter 

I've just noticed that this seems to have broken things here and there:
```
pbarker@bluebottle:/media/pbarker/pbarker250/APM/LOGS$ MAVExplorer.py 1.BIN 
Traceback (most recent call last):
  File "/home/pbarker/.local/bin/MAVExplorer.py", line 4, in <module>
    __import__('pkg_resources').run_script('MAVProxy==1.5.1', 'MAVExplorer.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.5.1-py2.7.egg/EGG-INFO/scripts/MAVExplorer.py", line 491, in <module>
    
  File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.5.1-py2.7.egg/EGG-INFO/scripts/MAVExplorer.py", line 399, in loadfile
    
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/mavutil.py", line 1201, in mavlink_connection
    m = DFReader.DFReader_binary(device, zero_time_base=zero_time_base)
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/DFReader.py", line 516, in __init__
    self.init_clock()
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/DFReader.py", line 362, in init_clock
    m = self.recv_msg()
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/DFReader.py", line 441, in recv_msg
    return self._parse_next()
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/DFReader.py", line 587, in _parse_next
    self._add_msg(m)
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/DFReader.py", line 464, in _add_msg
    mapping = mavutil.mode_mapping_bynumber(self.mav_type)
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.0.6-py2.7-linux-x86_64.egg/pymavlink/mavutil.py", line 1557, in mode_mapping_bynumber
    mav_autopilot = self.field('HEARTBEAT', 'autopilot', None)
NameError: global name 'self' is not defined
^CError in atexit._run_exitfuncs:
```

**Comment by LorenzMeier** [comment]
Sounds like our CI tests are bad. I will revert. Can you propose a test which covers this?

**Comment by LorenzMeier** [comment]
Reverted. Now on to re-do this in a way which is not breaking things.

**Comment by LorenzMeier** [comment]
Here is the new PR: https://github.com/mavlink/mavlink/pull/612

**Pull request merged**
