### PR TITLE
DISTANCE_SENSOR: changed to SI units

### PR DESCRIPTION
**Pull request by TSC21**

### CODE REVIEW

**Comment by vooon** [comment]
In INT?

**Comment by TSC21** [comment]
@vooon INT?

**Comment by bansiesta** [comment]
Please change this to float. There is no point in having meters in uint16 :).

**Comment by TSC21** [comment]
@bansiesta will do.

**Comment by LorenzMeier** [comment]
We can't do this - it would result in incompatibility with deployed systems. I proposed to leave it at scaled integers.

**Comment by LorenzMeier** [comment]
@TSC21 Not sure if anything is left in this PR then. If not please close.

**Comment by TSC21** [comment]
@LorenzMeier ok. @bansiesta then we should double check if published distances are in cm and the subscribed distances are in meters (subscribed distances in the estimators, mainly), so we don't have problems with scales. Closing now.

**Pull request closed without merging**
