### PR TITLE
common.xml: remove MAV_SENSOR_ROTATION_ROLL_270_YAW_180 it messes Ard…

### PR DESCRIPTION
**Pull request by amilcarlucas**
…upilot up

### CODE REVIEW

**Comment by hamishwillee** [comment]
@amilcarlucas Can you please explain how? Do we know if anyone is using this?

**Comment by auturgy** [comment]
is roll 270 yaw 180 different to roll 90 pitch 180 (ie orientation 31)?

**Comment by amilcarlucas** [comment]
@tridge ask me to remove these lines from our fork because they cause problems. For more details you need to ask him directly

**Comment by hamishwillee** [comment]
@tridge Can you please explain (or get @auturgy to bring to the dev call)? I will ask @julianoes for comment on whether there were other reasons for this too, but he isn't back until January.

**Comment by dagar** [comment]
The duplicates cause problems in PX4 as well (automatically determining rotation, etc). I'd be happy to remove them if we can get away with it.

 - ROTATION_PITCH_180_YAW_90 (26) = ROTATION_ROLL_180_YAW_270 (14)
 - ROTATION_ROLL_180_YAW_90 (10) = ROTATION_PITCH_180_YAW_270 (27)
 - ROTATION_ROLL_90_PITCH_180 (31) = ROTATION_ROLL_270_YAW_180 (41)

**Review by dagar — APPROVED** [review]

**Comment by hamishwillee** [comment]
@amilcarlucas All good, but perhaps add a comment in the source to indicate these were deliberately removed so that no one adds them back again in future.

**Pull request merged**
