### PR TITLE
common.xml: added VTOL takeoff and land commands

### PR DESCRIPTION
**Pull request by tridge**
This makes for clearer missions for VTOL aircraft capable of fixed wing flight
than using DO_VTOL_TRANSITION

### CODE REVIEW

**Comment by LorenzMeier** [comment]
There are two unused params each in takeoff and land which could be used to indicate the vehicle configuration - this would lower the implementation burden for GCS developers. I presume you're arguing that you're worried about uninitialised values for these fields?

**Comment by tridge** [comment]
are you proposing using those float fields as enums for type of takeoff/land?
I think they are a very different kind of operation you are asking the vehicle to do, and it would be clearer when editing a mission to see a NAV_VTOL_TAKEOFF than to see a NAV_TAKEOFF with a parameter set
Ideally I'd like to see GCS developers use the information from the mavlink XML files to auto-populate the mission editors. That is what I do now in MAVProxy and it means no work for the GCS developer to add new mission commands. Just recompile and the new mission commands automatically appear.
The C generator for mavlink doesn't yet generate enough information to do this properly while the python one does. We should improve the C generator I think.

**Comment by LorenzMeier** [comment]
Ok. QGC does support it already: https://github.com/mavlink/qgroundcontrol/commit/7580d24cb87e38375ebee05bb0a3e0156134f918

So what we lack is mostly the JSON generation & docs.

**Comment by LorenzMeier** [comment]
Applied!

**Comment by DonLakeFlyer** [comment]
> Ideally I'd like to see GCS developers use the information from the mavlink XML files to auto-populate the mission editors.

Mavlink submodule needs to change such that the XML files are in the submodule as well. Is there a way to do this now?

**Comment by LorenzMeier** [comment]
Yeah, we can just have the build script copying the message specs to the binary module as well.

**Comment by DonLakeFlyer** [comment]
That would allow MavCmdInfo.json to only be needed for friendly edit suppored commands. Raw edit could be done automatically. Only need common.xml for that. Having the message specs xml would also allow me to create the MavLink fact provider which I have had in the back of my head forever. This would give access to all mavlink information directly to Qml. The opens up lots of interesting things from a custom command standpoint. Not to mention would get rid of most of UAS.cc which tends to mostly be a bridge between mavlink messages and signalling.

**Pull request closed without merging**
