### PR TITLE
Add MAV_BATTERY_CHARGE_STATE_CHARGING

### PR DESCRIPTION
**Pull request by okalachev**
I propose adding a charging state of the battery.

This enum value would be useful for systems with automatic charging stations.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Makes sense to me, and there is no compatibility issue. @auturgy @LorenzMeier @MaEtUgR - any thoughts on this one?

**Comment by MaEtUgR** [comment]
Ah but I just saw it should probably say "Enumeration for ~low~ battery states." in the description of the enum.

**Comment by hamishwillee** [comment]
Thanks @MaEtUgR !

@okalachev IMO better even to say "Enumeration for battery charge states." in the description. THoughts?

**Comment by auturgy** [comment]
Sounds good 

Regards,

James

**Comment by okalachev** [comment]
@hamishwillee, ok, done!

**Comment by hamishwillee** [comment]
Thanks @okalachev , all. Merged.

**Pull request merged**
