### PR TITLE
MAV_CMD_REQUEST_MESSAGE: Define that parameters can be used

### PR DESCRIPTION
**Pull request by hamishwillee**
This allows us to request messages using MAV_CMD_REQUEST_MESSAGE where the value of the returned message can be conditional on values passed to the target system.

In most cases message don't depend on parameters and the new params should be set to zero. In cases where parameters are expected, the values of the params must be specified in the message that is requested.

### CODE REVIEW

**Comment by julianoes** [comment]
I don't understand what this is used for.

**Comment by hamishwillee** [comment]
An example is requesting the [service version](https://docs.google.com/document/d/1zK_JcJbhtbRA3W0MgnXSNWMUxOcBu6vXocrjZVMXki4/edit?ts=5de097ca#heading=h.q82gs8qw8s1). The information you get back depends on what you put in.

I don't see this as particularly confusing, but I do see that it isn't quite so encapsulated a design as having (in this case) a separate message.

**Comment by julianoes** [comment]
@hamishwillee so where do we document param3 and param4 which only matter for `MAVLINK_SERVICE_VERSION`?

**Comment by hamishwillee** [comment]
As it says in the MAV_CMD_REQUEST_MESSAGE definition here "The use of this parameter (if any), must be defined in the requested message. By default assumed not used (0)."

So, in `MAVLINK_SERVICE_VERSION` you would have a description that says something like

> This message is emitted in response to MAV_CMD_REQUEST_MESSAGE , where param 3 is X and param 4 is Y (other params should be set to zero)

**Comment by julianoes** [comment]
Ok fine. I don't have a better suggestion.

**Comment by hamishwillee** [comment]
@julianoes I like the idea of this message; it is convenient to be able to request whatever we like without having to create a new message. But perhaps this is a "step to far."

The alternative is to simply decide that this can only be used to request messages that have no "configuration". The implication is that you couldn't use this for cases like the microservices versioning. 

I actually don't have a particular problem with that; a microservice having a dedicated messages feels more "encapsulated".

But if you say nothing in the next couple of days I propose to merge this. Doesn't mean we shouldn't still have dedicated messages for this microservice case though.

**Comment by julianoes** [comment]
I think we should still have a dedicated command for the microservice handshake.

**Comment by hamishwillee** [comment]
I agree. I'll merge this anyway though.

**Pull request merged**
