### PR TITLE
Added angle_z to LANDING_TARGET

### PR DESCRIPTION
**Pull request by djnugent**
See issue #431

### CODE REVIEW

**Comment by TSC21** [comment]
I would rather prefer a quaternion field:
`q[4]`

**Comment by djnugent** [comment]
I am not educated on quaternions. I know they are better but have no idea
what they are. Enlighten me. How do they improve this message? Arducopter
doesn't use quaternions, wouldnt it be an inconvenience to convert to
quaternions, send message, and then back to Euler once received?

Daniel

**Comment by TSC21** [comment]
> I am not educated on quaternions. I know they are better but have no idea what they are. Enlighten me.

http://www.cprogramming.com/tutorial/3d/quaternions.html

> How do they improve this message?

They give 3D spatial orientation of the target. With just adding yaw, you are assuming that the target is in a flat surface, with no rotation on XY plane, which may not be entirely true.

> Arducopter doesn't use quaternions, wouldnt it be an inconvenience to convert to quaternions, send message, and then back to Euler once received?

I think they have ways of converting this to Euler angles. Anyhow, that conversion would be trivial.

**Comment by mhkabir** [comment]
Hi people, as I said before, and am saying again, can we please have the option to send the full target pose. If a particular framework is not capable of providing the full pose (e.g IRLock), let those fields remain zeroed. 
Also maybe have a bitmask to declare the capabilities of the framework (full pose, only orientation, only position, etc.)
https://github.com/ProjectArtemis/aprilslam

**Comment by LorenzMeier** [comment]
@djnugent Not going to apply this. Please use a full quaternion.

**Comment by LorenzMeier** [comment]
Superseded.

**Pull request closed without merging**
