### PR TITLE
common: SCALLED_PRESURE: add press diff temperature

### PR DESCRIPTION
**Pull request by IamPete1**
Adds a second temperature field to SCALLED_PRESSURE to allow sending back of the air temp from the airspeed sensor. This is often quite different to the baro temp due to location. 

https://github.com/ArduPilot/mavlink/pull/142

### CODE REVIEW

**Comment by hamishwillee** [comment]
If this will not always be sent, you should define a value to represent "not sent" usually the max value for an int.

Given that we have three of these messages is it worth designing a single new one with an index? I'm asking, not advocating. @julianoes @auturgy

**Comment by hamishwillee** [comment]
OK then. In it goes. Thanks!

**Comment by amilcarlucas** [comment]
Using UINT16_MAX on a int16 type is wrong !!!!

**Comment by IamPete1** [comment]
@amilcarlucas Opps, your right, I think we should be using 0 for 'no value' in any case since its a extension.

**Comment by hamishwillee** [comment]
@amilcarlucas Good catch :-0. 

@IamPete1 can you create PR to fix?
I don't think it is too late as you're likely the only implementer at this point. Yes the default value should be 0 for not supported on an extension. Usually we'd use 0 indicates not supported and perhaps say 1 is used for 0 or 1

**Pull request merged**
