### PR TITLE
Update pymavlink to latest

### PR DESCRIPTION
**Pull request by hamishwillee**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@LorenzMeier @julianoes What checks need to be done for merging the pymavlink submodule (other than the CI tests)? ie can I just update this and auto merge whenever I like?

**Comment by hamishwillee** [comment]
FYI This is needed for https://github.com/mavlink/mavlink/pull/1023

**Comment by amilcarlucas** [comment]
This can AFAIK be merged

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by amilcarlucas** [comment]
Usually it is always safe to merge the latest pymavlink version. @tridge and @peterbarker are very careful to not introduce regressions.
One nice thing about this particular update is python3 support :)

**Pull request merged**
