### PR TITLE
common.xml:add display bitmap/remove units from description

### PR DESCRIPTION
**Pull request by hamishwillee**
Fixes suggested by @amilcarlucas

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dogmaphobic YOu OK with this. It makes sense to me, but not my message.

**Comment by amilcarlucas** [comment]
Please use the "Rebase and merge option"

**Comment by dogmaphobic** [comment]
> YOu OK with this. It makes sense to me, but not my message.

Sure! Though I think I already did the "in bits per second" part on another PR.

**Comment by hamishwillee** [comment]
@dogmaphobic Yes you did. I'll close this now - lots of minor fixes crossing over each other.

**Pull request closed without merging**
