### PR TITLE
Generate common message specs in gitbook format

### PR DESCRIPTION
**Pull request by hamishwillee**
Script generates a file message-definitions.md that can be imported into a gitbook. This depends on XSL file being added to master.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar OK, so this is PR to get the common message specs into gitbook format.

Can I leave you with the job of running this script when needed and copying the generated file into the english tree [here](https://github.com/mavlink/mavlink-devguide/tree/master/en), master branch ?

**Comment by dagar** [comment]
Sure, but let's make some simple notes for all these gitbook imports.

**Comment by hamishwillee** [comment]
@dagar Good idea. I've added a readme.

Are we likely to have more message definitions or related commands?
If so, then the output should perhaps be renamed to "common.md" or "common_definitions.md" and when copied into the gitbook moved to **/message_definitions/common.md**

**Comment by hamishwillee** [comment]
@bkueng Just Python 3. Is that OK?

**Comment by bkueng** [comment]
I'd add python 2 support as well, since it's still in use (preferred), or make sure python 3 is used: `#! /usr/bin/env python3`.

**Comment by hamishwillee** [comment]
@bkueng Thanks. Testing shows it works for both :-) I added a note in the docs section of the script. Merging this now.

**Pull request merged**
