### PR TITLE
Follow up PR for UTM_GLOBAL_POSITION

### PR DESCRIPTION
**Pull request by eyeam3**
There have been requested changes open from #1009. This is the follow up PR to address them as well.

- Add centisecond as unit to update_rate field
- Add missing display tag

Related to ArduPilot/pymavlink#242

### CODE REVIEW

**Comment by hamishwillee** [comment]
@eyeam3 Thanks for being so fast. There doesn't seem to be a process for automatically updating the submodule dependency. I've created a PR for this (see link above).

**Comment by hamishwillee** [comment]
@eyeam3 I've pulled in latest Pymavlink and tests now pass - so this can be approved. Can you confirm nothing else needs to change/that this can be merged?

**Comment by eyeam3** [comment]
Should be good to go. These were the open requests from the previous PR and the discussion around it.

**Comment by hamishwillee** [comment]
Merging as this has previously been reviewed/approved, it is a WIP message, and it builds without error.

**Pull request merged**
