### PR TITLE
common: Add missing bitmask in PLAY_TUNE_V2

### PR DESCRIPTION
**Pull request by patrickelectric**
bitmask exist in SUPPORTED_TUNES but not in PLAY_TUNE_V2

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by hamishwillee** [comment]
@LorenzMeier @patrickelectric I think this change is incorrect. The bitmask attribute allows a GCS to understand that the values can be treated as bitmasks - ie you can have multiple bits set and OR the result. That makes no sense for PLAY_TUNE_V2 because you can only ask a system to play a tune in one format at a time.

It is OK (but not particularly useful) for SUPPORTED_TUNES because a system can in theory support multiple tune formats and tell you all of them.

**Comment by patrickelectric** [comment]
@hamishwillee I thought that was the original idea behind the message and that's why I asked for you review.
My problem was related to https://github.com/mavlink/rust-mavlink where such message was breaking our code generator, it was the only one using a bitmask variable type without the bitmask xml tag. Be free to revert if necessary.

**Comment by hamishwillee** [comment]
Hi @patrickelectric ,
I don't particularly feel the need to revert, but can you please update your code generator to cope with the case that the variable might be missing?

**Pull request merged**
