### PR TITLE
Resource request

### PR DESCRIPTION
**Pull request by LorenzMeier**
@davids5 @DonLakeFlyer The intent behind this message is to:

1) Let the autopilot ask for a URI
2) Let the GCS download that file from the internet
3) Let the GCS upload the file via MAVLink FTP to the autopilot

We need to work out the complete sequence, but it would be great to get the support to initiate a MAVLink FTP upload via this message into QGC soonish, so that we can grab UAVCAN firmware binaries from the internet.

### CODE REVIEW

**Comment by davids5** [comment]
@LorenzMeier @DonLakeFlyer @Pavel-Kirienko

The file name format is: 
```
<uavcan_name>-$(UAVCANBLID_HW_VERSION_MAJOR).$(UAVCANBLID_HW_VERSION_MINOR)-$(UAVCANBLID_SW_VERSION_MAJOR).$(UAVCANBLID_SW_VERSION_MINOR).<git hash[8]>.uavcan.bin
```
For example
```
org.pixhawk.px4cannode-v1-1.0-0.1.9bd57372.uavcan.bin
<uavcan_name> is org.pixhawk.px4cannode-v1
```

As you can see the name lends itself to finding the file.

The structure on the SD card is as follows.

```
/fs/microsd/
fw
├───c
└───org.pixhawk.px4cannode-v1
    └───1.0
```

The use of the c directory is due to limitations on path length and uavcan internals

1. UAVCAN FirmwareFilePath is 40
2. NUTTX  is using 32 for max file names.

```
  /* This is a work  around for two issues.
         *  1) UAVCAN FirmwareFilePath is 40
         *  2) NUTTX  is using 32 for max file names.
         *
         *  So for the file:
         *    org.pixhawk.px4cannode-v1-1.0-0.1.9bd57372.uavcan.bin
         *    +---fw
         *        +-c        <----------------------------------- Files are cashed here.
         *          +--- 9bd57372.bin  <------------------ An unknown Firmware file
         *        +---org.pixhawk.px4cannode-v1 <-- node_info.name <uavcan_name>
         *        +---1.0 <------------------------------------- node_info.name's hardware_version.major,minor
         *            + - 9bd57372.bin <-------------------- A well known file must match the name
         *                                           in the root fw/c folder, so if it does not exist
         *                                           it is copied up
         */
   
```
 So to update a fw one would: 

1. Download the file.
2. Check if a directory exists or create a directory ```/fs/microsd/fw/<uavcan_name>```
2. Check if a directory exists or create a directory ```/fs/microsd/fw/<uavcan_name>/<hwmaj>.<hwmin>```
3. copy the new fw file, renaming it to ```<git hash[8]>.bin``` to directory ```/fs/microsd/fw/<uavcan_name>/<hwmaj>.<hwmin>```
4. If ```/fs/microsd/fw/c/<git hash[8]>.bin```  exist, delete it.
5. copy ```<git hash[8]>.bin``` to /fs/microsd/fw/c (It is better done here to speed boot loading)
6. use the command uavcan update fw or reboot,

N.B. The 32 character file name length on Nuttx Fat will require the copying to not use the full name as it will truncate.

**Comment by pavel-kirienko** [comment]
Let me just introduce a minor correction here: UAVCAN does not impose any sensible limits on the file name length. The restriction is specific to libuavcan, it's an implementation shortcoming, and it should be lifted in future versions of the library (again, nothing to do with specification).

**Comment by davids5** [comment]
Just an FYI:We will need to include the <uavcan name> in the files. Updated above.

**Comment by LorenzMeier** [comment]
@peterbarker heavily related to your log streaming case, just into the other direction.

**Comment by pavel-kirienko** [comment]
@davids5 @LorenzMeier What is the status now? Will the feature become available in any of the upcoming releases? Is the whole concept of domain name reversal etc. documented anywhere?

**Comment by davids5** [comment]
@pavel-kirienko 

On second Question: At this point this is the https://github.com/mavlink/mavlink/pull/414#issuecomment-120088482 docs

**Comment by pavel-kirienko** [comment]
@davids5 The part that is internal to PX4 is clear, my question was rather concerning the step "1. Download the file".

**Comment by davids5** [comment]
@pavel-kirienko - Let's design  it here in pseudo code


```
org.pixhawk.px4cannode-v1-1.0-0.1.9bd57372.uavcan.bin
<uavcan_name> is org.pixhawk.px4cannode-v1
```

Form a url
```
uavcan_name = org.pixhawk.px4cannode-v1

glue = "."
dn_pieces = split(glue, uavcan_name);
device_name =  dn_pieces[size(dn_pieces)-1];
unset(dn_pieces[size(dn_pieces)-1]);
dn_pieces = reverse(dn_pieces);
host = join(glue, dn_pieces);
url = "http://" + host + "/uavcan_fw/" + device_name;
``

The url returns a zip file uavcan_fw.zip

which has 
```
org.pixhawk.px4cannode-v1
    └───1.0
     |          + px4cannode-v1-1.0-9bd57372.bin
    └───1.6
     |          + px4cannode-v1-1.6-9bd57372.bin

image
```

**Comment by pavel-kirienko** [comment]
This is a good start. Let me introduce a few suggestions:

1. The proposed URL template has two drawbacks: 1. it may conflict with existing content of the website; 2. it may be a challenge for future modifications and extensions. I propose to move UAVCAN-related content to a subdomain: `"http://uavcan." + host + "/firmware/" + device_name`.

2. Considering the ubiquitous paranoia over security, shouldn't we use https, leaving http only as a fallback option?

3. Name of the returned archive is irrelevant, there's no need to explicitly specify it.

4. Internal structure of the archive should be simplified - I wouldn't trust vendors to always get it right, hence ugly workarounds will likely come into existence at some point. A simpler structure would be just a flat directory with files named following the convention `org.pixhawk.px4cannode-v1-1.0-0.1.9bd57372.uavcan.bin`. The receiving side will then reorganize the structure as it pleases.

Here's pseudocode with my suggestions considered:

```
uavcan_name = org.pixhawk.px4cannode-v1

glue = "."
dn_pieces = split(glue, uavcan_name);
device_name =  dn_pieces[size(dn_pieces)-1];
unset(dn_pieces[size(dn_pieces)-1]);
dn_pieces = reverse(dn_pieces);
host = join(glue, dn_pieces);
file = get("https://uavcan." + host + "/firmware/" + device_name);
if not file
    # Probably warn the user at this point
    file = get("http://uavcan." + host + "/firmware/" + device_name);
```

Archive:

```
whatever.zip
├── org.pixhawk.px4cannode-v1-1.0-0.1.9bd57372.uavcan.bin
└── org.pixhawk.px4cannode-v1-1.6-0.1.9bd57372.uavcan.bin
```

Also I'm not sure if it's necessary to repeat device name in the binary file names in the archive, since it is already specified in the URL. Probably it won't hurt though, as this redundancy provides extra protection against misplaced binaries.

**Comment by davids5** [comment]
Looks good.

The subdomain may be an issues for some. We should confirm that it is acceptable with all stake holders or offer the alternate in a fall back.

file = get("https://" + host + "/uavcan/firmware/" + device_name);

I do not think https - is needed - it will add a requirement to manages certs (buy and renew)

**Comment by pavel-kirienko** [comment]
I'm not quite sure about HTTPS either. Since PX4/APM images don't seem to be concerned over this, it probably isn't necessary for UAVCAN too, at least for now.

A fall-back URL without subdomain is fine.

Updated logic:

```
uavcan_name = org.pixhawk.px4cannode-v1

glue = "."
dn_pieces = split(glue, uavcan_name);
device_name =  dn_pieces[size(dn_pieces)-1];
unset(dn_pieces[size(dn_pieces)-1]);
dn_pieces = reverse(dn_pieces);
host = join(glue, dn_pieces);
file = get("http://uavcan." + host + "/firmware/" + device_name);
if not file
    file = get("http://" + host + "/uavcan/firmware/" + device_name);
```

**Comment by davids5** [comment]
@LorenzMeier @DonLakeFlyer 

I think we have reached a consensus on the method to fetch files. How do we proceed?

**Comment by LorenzMeier** [comment]
Publish the request via uORB, I can add then the required logic to send the MAVLink message.

**Comment by DonLakeFlyer** [comment]
Using https puts all sorts of additional  cross platform install requirements on QGC. So don't use it if at all possible.

**Pull request closed without merging**
