### PR TITLE
Update pymavlink to latest

### PR DESCRIPTION
**Pull request by hamishwillee**
This is (specifically) to get the new version of the java libraries

### CODE REVIEW

**Comment by hamishwillee** [comment]
@peterbarker  I'm trying to merge the latest Pymavlink to get JS-NextGen but getting the following errors:

image

Any idea what I'd need to do to get the tests to pass?

**Comment by davidbuzz** [comment]
i suspect tests will probably pass again if you have mavgen.py in your path

**Comment by hamishwillee** [comment]
@davidbuzz Suggests this might fix the CI errors: https://github.com/ArduPilot/pymavlink/pull/500

**Comment by davidbuzz** [comment]
peter merged that PR, so can i ask u to update this PR to point to the lastest commit on pymavlink/master and we'll see if that fixes it?
 https://github.com/ArduPilot/pymavlink/commits/master 
  https://github.com/ArduPilot/pymavlink/commit/0e88456d42aff2323f307bafe44ad05680127bda

**Comment by hamishwillee** [comment]
Thanks @davidbuzz. Worked. Happy days :-)

**Pull request merged**
