### PR TITLE
Px4 modes (#603)

### PR DESCRIPTION
**Pull request by LorenzMeier**
* pymavlink: interpret px4 modes

* pymavlink: set px4 modes

* pymavlink: support px4 modes in mode_mapping*

@squilter @peterbarker The new PR. What can we improve on testing?

### CODE REVIEW

**Comment by squilter** [comment]
@mikaelferland @nacho-carnicero

Can we revert the modifications to `mode_mapping_byname()` and `mode_mapping_bynumber()`, and keep `mode_mapping()` and everything else? These two methods are broken (sorry). The reason I changed them in the first place was so that dronekit-python could use them, but it seems that dronekit/dronekit-python#652 doesn't use them anyway.

**Comment by MikaelFerland** [comment]
@squilter yes you can revert the modifications to mode_mapping_byname() and mode_mapping_bynymber(). I didn't use them because the PX4 Pro modes are not handled like APM.

**Comment by squilter** [comment]
@LorenzMeier Can you revert the change or give me push access so that I can do it?

**Comment by squilter** [comment]
ping

**Comment by LorenzMeier** [comment]
@squilter please just do the change in a new branch and send a new PR. ill merge that one then.

**Comment by LorenzMeier** [comment]
Applied from @squilter, closing.

**Pull request closed without merging**
