### PR TITLE
Added array containing all en(de)coding C functions

### PR DESCRIPTION
**Pull request by barthess**
Manual writing of switch-case decoding routine for every new project is
annoying me. So I aggregated all decoding functions in array of
function pointers. Now I just call function using msg_id as array index.
I know about code size increasing but:
1) This is totally optional feature (no usage - no size increasing)
2) FLASH in modern MCUs is cheap resource

### CODE REVIEW

**Comment by tridge** [comment]
I don't really see how this would be used. Won't you still need the switch statement to determine what to do with the message once decoded, or at least to cast to the right structure type?
Can you give a pointer to how this is used in practice?

**Comment by barthess** [comment]
In practice receiving thread allocates memory for decoded message and dispatches pointers to copies using linked list. After that it is headache of end point thread how to deal with received *void pointer. After the month of usage I see only one benefit: memory allocates in chunks with exactly known sizes. Memory pool of mavlink_message_t structures looks more suitable.
Conclusions:
1) decoding table unneded. I will delete it and update my pull request soon.
2) encoding table is pretty convenient and I want to see it in mavlink.

**Comment by barthess** [comment]
Done. PR updated.

**Comment by LorenzMeier** [comment]
Moved to a different repo since.

**Pull request closed without merging**
