### PR TITLE
Revert "Merge pull request #873 from TSC21/est_msgs"

### PR DESCRIPTION
**Pull request by julianoes**
This reverts commit b4efea1609631683c7b29f85571ba2f34a10116e, reversing
changes made to 56e28570a7557e62e95613d7bd13a96e8cf5e02e.

This is required because the ESTIMATOR_INNOV_COV message is way too long
and this slipped the review and CI.

@TSC21 @jgoppert sorry this slipped my review. I'm removing all for now. We have to add it again as part of a PR with another review and discussion.

### CODE REVIEW

**Comment by julianoes** [comment]
I'm merging this immediately because builds are broken.

**Comment by TSC21** [comment]
There was a rebase mistake. The only msgs that should got in were ESTIMATOR_STATE, ESTIMATOR_STATE_STD, ESTIMATOR_INOV and ESTIMATOR_INOV_STD. Can we fix this instead of completely remove all the msgs?

**Comment by TSC21** [comment]
You can check #667 commit history and see that @jgoppert actually removed thosr msgs for that same reason. I didn't realize one slip by me when rebasing.

**Comment by julianoes** [comment]
Ok, let's discuss it in the strategy call next week.

**Pull request merged**
