### PR TITLE
Conan package

### PR DESCRIPTION
**Pull request by galikrosentalik**
this enhancement gives the possibility to create conan package from the mavlink repository.
https://conan.io/

known issues:
* get_version method in conanfile.py requires deeper understanding in conan to work flawlessly.
* Submodules are currently not supported in conan architecture, we are using git clone in order to bypass the issue.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @galikrosentalik 
Thanks very much. My concern with this contribution is that we don't know how to maintain it and to someone coming to the repo it isn't clear what it is for. 

So, for example, it isn't clear if we have to do anything each time we make a new release and how we keep this up to date. 

So cautiously interested in taking this, but with more documentation in the file on usage. Might it also make sense to have this in a "package_manager" subdirectory with a README describing the content?

@auturgy Have you any thoughts on this?

**Comment by auturgy** [comment]
We need to have a think about package management more generally: the only “managed” package is pymavlink, but there are maven and nuget examples also floating around that should be gripped up.
My suggestion would be to automate the package generation based on mavlink releases, but we’d need to actually do mavlink releases....

Regards,

James

**Comment by hamishwillee** [comment]
@galikrosentalik Also, this has `license = "Tevel"`. What does that mean?

@auturgy Thanks & yes. Unfortunately that's a bigger project that we both know won't progress quickly. What I'm trying for is a holding pattern solution that leaves us no worse off and means we're better prepared to organise similar contributions in future.

**Comment by hamishwillee** [comment]
@galikrosentalik Thanks for license update. Can you give us your thoughts on docs for this script?

**Comment by galikrosentalik** [comment]
hey hamishwillee & auturgy, 
I appreciate very much your comments.
It does seem that the issues regarding package management should be considered cautiously.
I think that in order to promote the issue, we need to start somewhere.. 
Conan seems like a good position as an industry standard for managing c++ packages , supported by jfrog.
I sure agree that a well documentation is needed(this will be included in my next commit).

**Comment by galikrosentalik** [comment]
hey hamishwillee & auturgy,
we had some discussion in my office regarding this pull request, after considering your comments.
the controversy is regarding the right place for the conan management, is it in the mavlink or in the mavlink generator. 
if we displace it to the pymavlink repository, so additionally in creating the cpp header files you could ask it to generate the conanfile as well.
I would appreciate your opinion.

**Comment by hamishwillee** [comment]
@galikrosentalik Re https://github.com/mavlink/mavlink/pull/1291#issuecomment-582280906 While I tend to think "here" is the right place I don't have a strong opinion.

How about you raise the question in as an issue in ArduPilot/Pymavlink (cross link here). The generator maintainers mostly live there. They may have a view.

Worse case, once this is documented with clear instructions on how it might be maintained then we can take it.

**Comment by hamishwillee** [comment]
Closing. Thanks for this, but not clear to me that this is needed or can be maintained.

**Pull request closed without merging**
