### PR TITLE
add MAV_CMD_DO_CHANGE_ALTITUDE

### PR DESCRIPTION
**Pull request by dagar**
The goal is to assign gamepad buttons for changing altitude +- 100m for altitude control, loiter, etc.

### CODE REVIEW

**Comment by magicrub** [comment]
How is this different than MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT or MAV_CMD_CONDITION_CHANGE_ALT?

**Comment by dagar** [comment]
MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT - only nav mode, only absolute altitude, interrupts mission until complete

MAV_CMD_CONDITION_CHANGE_ALT - delays mission, must specify the rate, only absolute altitude

If I'm in altitude control I want to be able to increase my altitude by X with a single click, and not have to fiddle with stick input. MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT definitely sounds the wrong command. MAV_CMD_CONDITION_CHANGE_ALT is closer, but I shouldn't have to specify the rate.

**Comment by magicrub** [comment]
sounds like what you want is MAV_CMD_CONDITION_CHANGE_ALT without the rate change. Perhaps changing that command instead of adding a new one is a better solution?

**Comment by DonLakeFlyer** [comment]
Isn't change altititude only, just new new REPOSITION command with everything but alt set to NaN?

**Comment by LorenzMeier** [comment]
@dagar Could you wrap this up so we can proceed?

**Comment by dagar** [comment]
Alright, so we have 3 options.

MAV_CMD_CONDITION_CHANGE_ALT - modify to work without specifying a rate, add option for relative altitude
MAV_CMD_DO_REPOSITION - modify to allow NaN Lat/Lon, add option for relative altitude change. Does it make sense for altitude control mode to respect a reposition command?
MAV_CMD_DO_CHANGE_ALTITUDE - new message, intended to be consistent with MAV_CMD_DO_CHANGE_SPEED

I don't have much experience working directly with mavlink. Could someone that's more familiar pick the option that's most consistent with current usage? How do we handle potentially breaking the existing usage of a message like MAV_CMD_CONDITION_CHANGE_ALT?

**Comment by magicrub** [comment]
Intentionally sending as NaN sounds like a terrible idea to me.

**Comment by DonLakeFlyer** [comment]
That’s the spec for the other fields in MAV_CMD_DO_REPOSITION. Why not for lat/lon? If prevents the need for creating a pile of new commands.

**Pull request closed without merging**
