### PR TITLE
Update mavlink_types.h

### PR DESCRIPTION
**Pull request by barthess**
Fixed bug "warning: declaration does not declare anything"

### CODE REVIEW

**Comment by vooon** [comment]
This changes accessors, e.g. `param.int16` → `param.__data.int16`, that looks ugly.

**Comment by barthess** [comment]
without that fix following code:
```C
mavlink_param_union_double_t mavp;
mavp.int16 = 0;
```
produces error
error: 'union mavlink_param_union_double_t' has no member named 'int16'

**Comment by vooon** [comment]
Hmm, without fix #352 (last released mavlink for ros) following code compilling without a problem:

```
#include <mavlink/v1.0/common/mavlink.h>

int main(int argc, char *argv[])
{
	mavlink_param_union_double_t p;

	p.int16 = 0;

	return 0;
}
```

```
gcc test.c -o t -I/opt/ros/jade/include
```

Then i added struct name (current `__data`) and got:
```
In file included from /opt/ros/jade/include/mavlink/v1.0/common/../protocol.h:5:0,
                 from /opt/ros/jade/include/mavlink/v1.0/common/common.h:30,
                 from /opt/ros/jade/include/mavlink/v1.0/common/mavlink.h:25,
                 from test.c:1:
/opt/ros/jade/include/mavlink/v1.0/common/../mavlink_types.h:98:6: warning: declaration does not declare anything
     };
      ^
/opt/ros/jade/include/mavlink/v1.0/common/../mavlink_types.h:13:40: note: in definition of macro ‘MAVPACKED’
   #define MAVPACKED( __Declaration__ ) __Declaration__ __attribute__((packed))
                                        ^
test.c: In function ‘main’:
test.c:7:3: error: ‘mavlink_param_union_double_t’ has no member named ‘int16’
  p.int16 = 0;
   ^
zsh: exit 1     gcc test.c -o t -I/opt/ros/jade/include
```

**Comment by vooon** [comment]
Then i applying your patch and got expected error:
```
test.c: In function ‘main’:
test.c:7:3: error: ‘mavlink_param_union_double_t’ has no member named ‘int16’
  p.int16 = 0;
   ^
zsh: exit 1     gcc test.c -o t -I/opt/ros/jade/include
```

And changing to `p.__data.int16 = 0` fix build.
So seems that #352 broke first.

**Comment by barthess** [comment]
Confirmed.

**Comment by vooon** [comment]
@barthess I think that this closed by this: https://github.com/mavlink/mavlink/commit/c6b5a128479bd36c8389952172dc8efac8069aed

But i not tested.

**Comment by vooon** [comment]
Tested: **fixed**.

**Pull request closed without merging**
