### PR TITLE
add GIMBAL_MANAGER_SET_TILTPAN, rename MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN

### PR DESCRIPTION
**Pull request by olliw42**
does https://github.com/mavlink/mavlink/issues/1376

for the units in GIMBAL_MANAGER_SET_TILTPAN I have chosen rad and rad/s. This is in contrast to the units in the MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN command, which uses deg and deg/s. 

Since GIMBAL_MANAGER_SET_TILTPAN is also a "high level" API like MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN one might argue that deg would be better than rad, but I went with rad here since rad is used also in the GIMBAL_MANAGER_INFORMATION message.

in MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN I also did some changes in the descriptions in the field,to make things more uniform across the series of GIMBAL_XXX messages/commands.

### CODE REVIEW

**Comment by olliw42** [comment]
@julianoes @hamishwillee irrespective of gimbal manager details, renaming to MAV_CMD_DO_GIMBAL_MANAGER_TILTPAN and adding GIMBAL_MANAGER_SET_TILTPAN makes IMHO sense in any case. It probably should be done rather sooner than later (at least the renaming).

**Comment by hamishwillee** [comment]
@julianoes Seems fine to me, but you get to approve. Please update the docs to go with this. 

FWIW I have no strong feelings on deg vs radians; I know Lorenz treats anything in MAVLink as low level and should use the most convenient mathematical units. High level would be SDK.

**Comment by olliw42** [comment]
commands are also used in missions
you know from scratch what 1.047 is?

**Comment by hamishwillee** [comment]
@olliw42 "you know from scratch what 1.047 is?". No, but the GCS could easily do conversions. FWIW I have no personal conviction on this, other than a desire for following common patterns.

Anyway, Julian is happy, so I have merged.

**Comment by olliw42** [comment]
great! THX.

**Pull request merged**
