### PR TITLE
Update message definitions to support GOPRO interface and Gimbal Axis Calibration

### PR DESCRIPTION
**Pull request by bugobliterator**
messages added by @arthurbenemann to support GOPRO interface and Gimbal Calibration.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Good to merge?

**Comment by bugobliterator** [comment]
Yes, in my opinion it is good to merge

**Comment by arthurbenemann** [comment]
The GoPro messages where added by @Gussy, the gopro enums are currently being modified by @liamstask .

The solo-gimbal messages will be cleaned up in a near future.

**Comment by LorenzMeier** [comment]
Is there an updated version of this already or can go in as-is?

**Comment by liamstask** [comment]
i suspect we may want to hold off on merging this, as the msg defs within solo may still be modified. if there's not too much concern about the churn that will introduce, these could go in now.

**Comment by LorenzMeier** [comment]
I'm closing this as stale.

**Pull request closed without merging**
