### PR TITLE
pymavlink improvements

### PR DESCRIPTION
**Pull request by Susurrus**
Added a way to filter the BAD_DATA messages out of the output from mavlogdump.py by outputting those messages to stderr. Now a simple command-line redirection can be used. Existing scripts should not be affected.

mavutil.py hasn't been updated in a while for parsing out timestamps and used old/outdated message fields to pull its data from. This has been corrected so that now all the timestamp information from common.xml is extracted. Behavior for datastamped logs should not be affected at all by this change.

I've also added a `TIMESTAMP_CUTOFF` for differentiating between uptime messages and those that are proper unix timestamps. It isn't used in this code, but would be used by user code that wanted to filter the output of mavlogdump.py.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tridge This PR looks like it needs mostly your vetting.

**Comment by tridge** [comment]
I'm not keen on the BAD_DATA change. Yes, it means you can use filter it out with shell redirects, but it also means if you don't want to filter it out you need different shell tricks (which will also change the order of the msgs, due to different buffering on stderr and stdout)
If you want to filter it out, I think either use grep -v in a pipeline or add an option to mavlogdump to make it filter out BAD_DATA.

The .mavlink extension is fine, and I've pushed that.

The timestamps will need a bit more testing and thought. The time_unix_usec as self.uptime looks wrong to me, and I think it would break mavgraph with --zero-time-base (which is an option I use a lot). We need to think about other impacts on tools that use pymavlink

**Comment by Susurrus** [comment]
What about a `--noerror` option for mavlogdump? Should this interact at all with the `--robust` option?

If boot time shouldn't be mixed in, than why is `time_boot_ms` already being used? I figured since those two were already there, throwing in the other 2 would work. But then again, I don't know what "work" really is in this case as I'm not sure what all this timestamp logic is supposed to do.

My use case for the improved time handling is that my datalogger just records the serial stream and has no concept of time to record in with it, so my system is more reliant on good timestamps on the incoming messages. And I

**Comment by tridge** [comment]
self.uptime is the board uptime. time_boot_ms gives us that. the unix timestamp is since unix epoch. So if we have a mix of them we could end up with lots of time jumps between packets.

I like the idea of a --noerror flag, which just drops BAD_DATA (or should be be called --no-bad-data ?)

**Comment by Susurrus** [comment]
From common.xml we have the following
  * **time_boot_ms** - Timestamp (milliseconds since system boot)
  * **time_usec** - Timestamp (micros since boot or Unix epoch)
  * **time_unix_usec** - Timestamp of the master clock in microseconds since UNIX epoch.

So `time_usec` is ambiguous, and could possibly change from a boot time to Unix epoch after a GPS fix has been acquired, so what could be done is use the `TIMESTAMP_CUTOFF` variable that I added to determine if the time is boot-relative or epoch-relative.

`--no-bad-data` is probably a better idea. So it just drops output of those messages? That should only be 2 lines.

**Comment by LorenzMeier** [comment]
@tridge Do you have further comments?

**Comment by tridge** [comment]
the patch should not be merged in its current form - it will break things due to the different time base for different timestamps.
A simple --no-bad-data PR would be welcome as a separate PR. 
The time_usec definition in common.xml is indeed bad, but differentiating time based on a cutoff isn't the solution I think. Note that mavutil.py does not use time_usec from any packet at the moment.
Right now the tools look for a GPS message to get base time, then use the time_boot_ms fields to interpolate from there. It works, even if it isn't elegant.

**Comment by Susurrus** [comment]
Is that time interpolation documented anywhere? I didn't see anything when I was digging around in this code, and it might help other people to have that procedure documented somewhere?

I'll try to get around to adding a `--no-bad-data` commit soon.

**Comment by tridge** [comment]
my apologies, the interpolation is in DFReader for DF logs. For mavlink log files it gets the time from the 8 byte header. For live mavlink streams it comes from system time on the receiver.
I agree it is a bit of a mess :(

**Comment by Susurrus** [comment]
Yeah, I have a datalogger now which doesn't timestamp things because it doesn't have an RTC or anything. I've been hoping MAVLink would get a little better at processing streams that don't have timestamps built-in, but it looks like that's not too common of a usecase.

**Pull request closed without merging**
