### PR TITLE
Add EXT_STATE_ESTIMATE_COV message

### PR DESCRIPTION
**Pull request by mhkabir**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Further discussions hinted that we only need the upper triangular matrix + diagonal since the covariance is symmetric, that should save quite some floats.

**Comment by mhkabir** [comment]
Let's put it into 2

**Comment by mhkabir** [comment]
Didn't mean to close that, sorry.

Let's put it into 2 arrays, for attitude and position separately.

**Comment by mhkabir** [comment]
@LorenzMeier Anything on this?

**Comment by LorenzMeier** [comment]
Did you do the triangular change yet? IF yes I missed it in the diff.

**Comment by mhkabir** [comment]
Nope. No time, sorry. IIRC, even with just the triangular, its too many.

**Comment by mhkabir** [comment]
@LorenzMeier Even with the upper triangular, I see no way to get this to fit. Its a 12x12 matrix for the full thing, so no. Perhaps dump the co-variance for now and come back to this later?

**Pull request closed without merging**
