### PR TITLE
add MAV_LANDED_STATE_LANDING

### PR DESCRIPTION
**Pull request by dagar**
https://github.com/mavlink/qgroundcontrol/issues/4935

@DonLakeFlyer @WickedShell

### CODE REVIEW

**Comment by magicrub** [comment]
is there a "takeoff_state"?

**Comment by dagar** [comment]
@WickedShell yes, and it changes the conversation somewhat if the extremely common stuff is covered elsewhere.

@magicrub I don't believe so. I definitely thought about adding that here as well, but it seemed questionable. What do you guys think?

**Comment by magicrub** [comment]
sounds like it doesn't hurt to add a takeoff flavor

**Comment by WickedShell** [comment]
@dagar cool, I'd quite like to get that in soon, but I do get why it's been held up.

I'm not terribly enthused about the LANDING_STATE/TAKEOFF_STATE ideas, but they do cover the generic cases well. I'm just not sure what the behaviour would be once you complete a takeoff/landing, do you keep sending the message?

**Comment by dagar** [comment]
@WickedShell EXTENDED_SYS_STATE (http://mavlink.org/messages/common#EXTENDED_SYS_STATE) is streamed at a relatively low rate in PX4. 

I've updated the PR with a takeoff state.

@DonLakeFlyer review?

**Comment by DonLakeFlyer** [comment]
Perfect. @LorenzMeier Can i merge?

**Comment by rmackay9** [comment]
100% agree we need a landed-state.  Very nice to see this being added.

I'm less sure about the need for a take-off state.  I don't think in general we should try to think too far ahead.  The only place where ardupilot might need a take-off state is for traditional helicopters in order to tell the GCS if the rotors have spun up completely or not.  I haven't heard anyone actually asking for that notification though.

**Comment by DonLakeFlyer** [comment]
Keep in mind that is is a "landing" state. Signalling that the vehicle is in the process of landing. Not a "landed" state. EXTENDED_SYS_STATUS already has values that indicate on the ground or in the air.

**Comment by rmackay9** [comment]
Ah right, OK.  So what I want is already there! thanks.

**Comment by LorenzMeier** [comment]
Thanks all!

**Pull request merged**
