### PR TITLE
ardupilotmega.xml: Fix possible UInt8 overflow in capture_mode field of GOPRO_HEARTBEAT message

### PR DESCRIPTION
**Pull request by modnovolyk**
Definition of entry `GOPRO_CAPTURE_MODE_UNKNOWN`:
```
<entry name="GOPRO_CAPTURE_MODE_UNKNOWN" value="255">
```
contradicts type requirements for `capture_mode` field in `GOPRO_HEARTBEAT` message:
```
<field enum="GOPRO_CAPTURE_MODE" name="capture_mode" type="uint8_t">Current capture mode</field>
```
as default generator implementation will generate `ENUM_END` flag entry by increasing last case value.
In this case  `ENUM_END` will be `GOPRO_CAPTURE_MODE_UNKNOWN + 1` (255 + 1)  that does not fit into UInt8.

Also I think it will be safer to use 0 by default for unknown (undefined) cases.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tridge This is yours

**Comment by Susurrus** [comment]
It should be noted that enums don't have datatypes in C, therefore there isn't any overflow per-say in the enum declaration. Is there testcode that uses the datatype of the field and the enum for that field to test things? In that code there would likely be an overflow then.

**Comment by modnovolyk** [comment]
Hi @Susurrus,
you are right, in fact the issue is not in enum itself, but in `capture_mode` field type (`GOPRO_HEARTBEAT` message). I've changed title of this issue.

I thought that fields in message definitions that have `enum` property set should be able to hold any of `enum` entries' raw value including `ENUM_END` flag entries` value. Correct me if I'm wrong.

It would be grate if someone could clarify logic behind `ENUM_END` flag. From generated C code (at least for current GOPRO_HEARTBEAT message) it looks like this flags' value is not used and could not be used even in theory.

**Comment by Susurrus** [comment]
ENUM_END only makes sense for checking if a value is valid, though this enum value is (IMO improperly) generated for enums that are not 0..N, like bitfields. I have never used this functionality in live code.

**Comment by modnovolyk** [comment]
Agree. ENUM_END does not have equitable meaning compared to other enum values. As Enumerations in Swift are first-class types i'll use static computable  property instead separate case value in enums for this purpose.

Thank for clarifying this.

So this PR is not valid anymore, I'm closing it.

**Pull request closed without merging**
