### PR TITLE
Remove 0.9 messages

### PR DESCRIPTION
**Pull request by hamishwillee**
As per https://github.com/mavlink/mavlink/issues/832 the 0.9 messages are confusing. This branch removes them. Further work will be required to fix test errors etc.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@julianoes Can we/should we also move the 1.0 messages into the parent folder - ie not have any message versioning in the folder tree. As it is now the version 1.0 is confusing because the folder contains both 1.0 and 2.0 messages. 
I guess we'd leave as-is if we expect versioning in future. Even then though, I'd think we'd be better off considering keep the parent level as "current messages" and pushing legacy message formats down into a lower tree.

**Comment by julianoes** [comment]
@LorenzMeier this is what I was referring to yesterday in the call.

**Comment by hamishwillee** [comment]
@julianoes Can we progress this? Fine not to do right now, but when should I chase you for next steps?

**Comment by julianoes** [comment]
I don't know. There is a bunch of mavlink work to be done that I have to push back for now.

**Comment by hamishwillee** [comment]
OK, I'm just going to take if off my "chase Julian" list for now. We'll talk about it again when/if you have time (or can suggest someone else).

**Comment by LorenzMeier** [comment]
I'll take a pass at this later this week. @amilcarlucas Any feedback from your end on removing v0.9?

**Comment by amilcarlucas** [comment]
We will discuss this on Monday at the ArduPilot Team meeting. I'll get back to you then.

**Comment by hamishwillee** [comment]
@LorenzMeier Yes. I will look at it again now I have a better understanding of the system.

I think it makes sense at same time to also move the whole tree up one - ie so all the definitions in 1.0 move up one level.  Thoughts? 

In dev meeting today we also discussed pushing these messages into their own repo. This is to help a few external generator developers to more easily include just the messages. ThomasG will discuss with you.

**Comment by hamishwillee** [comment]
@LorenzMeier 
1. This is blocked by https://github.com/mavlink/pymavlink/pull/15 - can you merge? 
    - Is it then OK for me to update the pymavlink submodule to current master? 
    - What testing needs to happen after that to verify nothing broke?

Does not affect this PR, but:
2. More generally, I understand there is a plan to drop mavlink/pymavlink and re-sync with ArduPilot/pymavlink. Is that correct? Timing?
3. This removes the 0.9 messages. We should also remove the underlying support for 0.9 in the generators, because any any attempt to use it will fail without them. I could do that, but would be best to have single fork of pymavlink first.

@amilcarlucas Did you have a chance to discuss this in meeting as per https://github.com/mavlink/mavlink/pull/835#issuecomment-367606995 ?
If not, I will put in agenda for next mavlink dev meeting

**Comment by amilcarlucas** [comment]
Going to ardupilot/pymavlink only introduces 2 regressions:
- Mavlink 2.0 Java support (that is half-broken in the fork anyways)
- Ignoring timestamps in Mavlink 2.0 signed messages (that is also a broken concept anyways)
Everything else is in there, I have kept the for up-to date, except the two features mentioned above because they did not got accepted upstream.

The last few weeks I was not able to attend the meeting, I hope that changes soon.
I would love to hear if my deprecated PR got accepted :)

**Comment by amilcarlucas** [comment]
Ardupilot does not use 0.9, It can go away.

**Comment by amilcarlucas** [comment]
Needs a rebase, but AFAIK upstream pymavlink changes are already in place to support this.

**Comment by hamishwillee** [comment]
Damn it, merged via github rather than rebased. Hope that breaks nothing.

**Comment by hamishwillee** [comment]
It fails at the same point, so is it possible mavlink/mavlink is using a changelist of pymavlink before the fix went in?

**Comment by amilcarlucas** [comment]
I re-triggered the CI. Let's see if it works now. Please do a clean rebase later before merging.

**Comment by hamishwillee** [comment]
@amilcarlucas Thank you. CI passed.

> Please do a clean rebase later before merging.

I had to force push but it looks good.

**Pull request merged**
