### PR TITLE
pymavlink: move maintainence to submodule

### PR DESCRIPTION
**Pull request by tridge**
This moves maintenance of pymavlink to a submodule. I think this provides a clearer separation of maintenance responsibilities. There have been too many pushes to pymavlink which break core functionality for a widely used project.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I don't see how moving it from a mavlink-focused repo to an autopilot repo help with that. The main issue is that there is a lack of CI sets and attention in terms of maintenance - there are heaps of unreviewed pull requests. I think the best we can do is to try to recruit more development bandwidth in order to offer more review bandwidth and a better CI system taking care of the main breakage.

**Comment by tridge** [comment]
@LorenzMeier, Peter and I are perfectly able to handle maintenance of pymavlink. Having an out of tree compiler works fine for both the px4 msg system and the dsdl compiler, so I don't think there is any reason to think it won't work for pymavlink too.
The basic problem is that the relationship we worked out regarding pymavlink is not working. Pymavlink was my project, created out of my work on mavproxy. We then came to an agreement where the pymavlink and mavlink projects would share a single git repository, with us being joint project leaders.
I expected a degree of professional respect as part of that agreement. When I asked you twice last month to support me being a representative for the mavlink project within DroneCode you didn't even bother to respond. Instead you worked with Chris and Mark to stage a coup within DroneCode to try and remove ArduPilot from DroneCode. I told you numerous times that I wanted to keep the collaboration going but you just ignored me.
On top of that you have been merging obviously broken PRs into pymavlink. I have discussed this with you several times before and yet you keep doing it. I can only assume you don't care about keeping pymavlink working for its users. Getting the PR count down is not the end goal of a project like pymavlink. Keeping a stable working and useful python library is the goal, and that is not done by merging PRs without proper review.
So our agreement to host pymavlink and mavlink in the one git repo is broken.
I am moving pymavlink back out of this repo. I think I am well within my rights to do this given I started the project and have been doing the vast majority of the work on maintaining it ever since.
I had high hopes for this collaboration but your actions over the last few months have made it one sided at best.
applied

**Comment by vooon** [comment]
That change completely break building mavlink for ROS. Bloom can not pull submodules, so i simply can't do buildable release.

**Comment by magicrub** [comment]
Simple solution is to change the url to use the new current /ardupilot/pymavlink one instead of the old /mavlink one.

**Comment by LorenzMeier** [comment]
MAVLink is a collaboration by many autopilot projects, so the best place will remain a central repository and there is no reason to disrupt that.

**Comment by tridge** [comment]
I did put a more detailed explanation for why I merged this PR but Lorenz deleted it.
It should not be too difficult to fix up users of the mavlink repo to cope with the submodule. We've coped with several submodule structure changes in PX4Firmware without issue.

**Comment by tridge** [comment]
@voon I guess the short term fix for ros would be to have two submodules, one for mavlink and another for pymavlink. It would be better to get vcstools fixed to handle submodules though.

**Comment by vooon** [comment]
Until bloom can't work with submodule only possible thing is to release pymavlink as third party ros package, then add it to depends for mavlink.

    pymavlink → mavlink → mavros (or other).

But problem here that pymavlink depends on message definitions from mavlink. That unsolvable.
So for near future i would not update pymavlink and only cherry-pick message definitions changes to mavlink2-cxx11 branch.

I'm not fully understand how separating to submodule can help with maintenance?

**Comment by OXINARF** [comment]
@vooon Have you tried reversing https://github.com/ros-infrastructure/bloom/commit/d522b72c6a9f3906373c0ad764a1ee7e90f8da1e? According to the issues in the bloom/vcstools repositories it should now work if that commit is reversed (since vcstools now supports exporting git repos with submodules).

**Pull request merged**
