### PR TITLE
common.xml: smart_battery_info fix cycles not available to UINT16_MAX

### PR DESCRIPTION
**Pull request by hendjoshsr71**
Changes cycle_count to an int32 to allow for -1 if not available

### CODE REVIEW

**Comment by LorenzMeier** [comment]
The issue with this change is that due to the hardening of the protocol, this message would be (intentionally) incompatible with its previous versions. How about you document instead that a value of UINT32_MAX indicates that it is not available?

**Comment by hendjoshsr71** [comment]
Makes sense! I changed it so that cycles not available is set to UINT16_MAX.

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
@auturgy I'm merging this right away since it is an obvious fix (-1 == UINT16_MAX for an unsigned int)

**Comment by auturgy** [comment]
@LorenzMeier no worries: we knew about this one

**Pull request merged**
