### PR TITLE
ardupilotmega.xml: merge changes from ardupilot repository

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! So now we just need to format all those files.

**Comment by jschall** [comment]
If that is what you want, I am happy to run the tool on them for you.

**Comment by LorenzMeier** [comment]
Yes - they key is to do a single commit per file which only includes the automatic changes and nothing else. Then the APM diff should actually expose what you really changed.

If we encounter issues with pending PR's we can ask people to run the tool locally to get them into shape. A bit of a pain but worth doing once.

The last missing bit would be to run the script on each file of a PR and to fail the PR if it resulted in a change - that way we force people to adhere to the code style even before committing. Worst case we can add that later.

**Comment by jschall** [comment]
Done

**Comment by jschall** [comment]
Build was failing - had to improve the tool to work around bad parsing. Fixed now.

**Comment by liamstask** [comment]
is a custom pretty printer necessary? wondering if we can use either `minidom.toprettyxml` or lxml's `pretty_print=True` option (if lxml is an option) when writing a doc.

**Comment by LorenzMeier** [comment]
I also have the impression that we shouldn't build our own custom tools but stick with something standard. We have to trust that the printer doesn't make mistakes. Why reinvent the wheel?

**Comment by jschall** [comment]
I investigated both of those tools and found them to be deficient.

It is really easy to review xmlpretty.py and confirm that it won't change non-text and non-comment elements.

**Comment by liamstask** [comment]
what were the issues with them?

**Comment by jschall** [comment]
IIRC output wasn't good - on one of them, every element got a newline, including text elements. It might work in combination with code to strip all of the text elements, but I'd rather have control over it.

Like I said, it is very easy to review xmlpretty.py to confirm that it won't change non-text or non-comment elements.

This PR stands as-is and if mavlink/mavlink doesn't want the tool that is already accepted and in use on ardupilotmega.xml in ardupilot upstream then the maintainers should feel free to not use it on the other XML files, and feel free to find other tools.

**Comment by LorenzMeier** [comment]
> This PR stands as-is and if mavlink/mavlink doesn't want the tool that is already accepted and in use on ardupilotmega.xml in ardupilot upstream then the maintainers should feel free to not use it on the other XML files, and feel free to find other tools.

I don't think that a technical discussion should ever end with that sort of argument (in particular on file formatting, which is something that in principle should not be hard to agree on or hard to be changed), but it has had enough social cost that I'm willing to put a cut here, adopt the file and much rather not continue the discussion. I'll try to understand if I come to the same conclusion about being trivial to review, if not, we'll try to use a properly configured standard tool on the other files (but keep the formatter in so the APM file can be formatted and policed with the right format).

I'm open and going to make and effort to try to adopt the file format for the other files. Thanks for the complete PR, people will certainly appreciate having less weirdly indented files.

**Comment by tridge** [comment]
I have pushed in just the tool and ardupilotmega.xml changes. We can do a separate PR for the other XMLs. I think however that the users of those XMLs should be the ones to run the formatting and do a PR. They should be able to test the changes in their environment and make sure it works for them, and should be able to check that the updates suitably handle their comments

**Comment by jschall** [comment]
Tridge merged the tool and ardupilotmega.xml, and I rebased the rest of this for Lorenz's convenience in applying the tool to the rest of the XML.

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by jschall** [comment]
@LorenzMeier totally happy for all of the files including ardupilotmega.xml to move to a standard tool if you find a good option. For me, writing one was the fastest route to the exact result that I wanted.

**Comment by mpaperno** [comment]
Please do not auto-format autoquad.xml.  It is messing up my descriptions (removing line breaks), and adding unnecessary blank lines to enums (those are just what I noticed on quick glance).

If there is a style guideline for MAVLink XML files, please pardon my ignorance and point me to it. I would rather choose to adhere to it manually than having my source reformatted for me.

Thanks,
-Max

**Comment by jschall** [comment]
OK. Closing this PR. I never cared that this tool apply to other files.

**Comment by jschall** [comment]
By the way you might reconsider your stance on unnecessary newlines as they can help to reduce merge conflicts.

**Comment by mpaperno** [comment]
I probably scroll through 50K lines of code a day, so my stance on *unnecessary* newlines is pretty firmly rooted.  :)  If they help some people, great, that should be their choice.  Personally I'd also hate to see common.xml become nearly twice as long, but maybe that's just me.

Cheers,
-Max

**Comment by jschall** [comment]
Fair enough. To each his own.

**Pull request closed without merging**
