### PR TITLE
pymavlink: update submodule

### PR DESCRIPTION
**Pull request by julianoes**
This brings more mavlink 2 support for the Java generator.

### CODE REVIEW

**Comment by magicrub** [comment]
great! I'd love to see more MAVLink v2 support in JAVA. @WickedShell can you take a peek at this?

**Comment by WickedShell** [comment]
This is definitely not stable enough to be merged (or really called MAVLink 2 support) yet, and I'm surprised to see it in the pymavlink submodule.

Generating MAVLink2 with anything that includes the uAvionix XML file (IE ardupilotmega.xml) can not be compiled as none of the uAvionix messages are included in `MAVLinkPacket` even though the messages appear in the case statement.

Haven't had time to review the implementation side yet, but at the moment this is not a usable addition.

**Comment by julianoes** [comment]
@WickedShell thanks for the feedback.

I did not claim that this brings full mavlink 2 support but it gets us closer.
Does this break anything? If yes, please help identify the cases. If not, I think it makes sense to merge this and add more (or the full) mavlink 2 functionality later.

**Comment by julianoes** [comment]
@WickedShell also note that there is also [a fork of Pymavlink used for ArduPilot](https://github.com/ArduPilot/pymavlink).
I'm not saying we should diverge (I think we should not) but just wanted to point that out.

**Comment by WickedShell** [comment]
@julianoes it's a fundamental breakage in that it's not generating/handling multi file xml's correctly, and the purpose of adding MAVLink2 support is broken in that scenario so badly that a user can't compile (not just can't speak MAVLink2). (And given that the listed feature of MAVLink2 doesn't work for a significant use case all I can really see is a fair amount of overhead being added to MAVLink1 decoding without being a more complete parser).

I realize it's different repo's for some reason but breaking the build doesn't seem like a great choice either. For the record I suspect https://github.com/ArduPilot/pymavlink/pull/122/ might resolve it but I don't have time to actually test it until later this week.

**Comment by julianoes** [comment]
@WickedShell I understand. I'm not up to speed with the mavlink dialects and the changes mavlink 2 brings.

All I know is that the changes here are needed to talk to a vehicle that sends mavlink 2.

I'm ok with waiting for ArduPilot/pymavlink#122 and then re-evaluate.

**Comment by julianoes** [comment]
@WickedShell since ArduPilot/pymavlink#122 is merged, could this PR now be considered?

**Comment by magicrub** [comment]
needs rebase

**Comment by julianoes** [comment]
> needs rebase

Done

**Comment by julianoes** [comment]
Any objections to merging this @WickedShell? Or is there something specific I should look into and test? I'm not very familiar with all pieces here, so I'd need some guidance, thanks.

**Comment by WickedShell** [comment]
@julianoes Not sure you rebased it correctly/as intended. I can't find the relevant patch set in the PR, nor do I see it merged in the mavlink/pymavlink repo. As far as I can tell the relevant files haven't changed at all anywhere yet on the mavlink fork. FWIW as it stands at the moment it's still a compile failure.

```
/home/wickedshell/code/SwiftGCS/src/java/com/MAVLink/MAVLinkPacket.java:922: error: cannot find symbol
            case msg_uavionix_adsb_out_cfg.MAVLINK_MSG_ID_UAVIONIX_ADSB_OUT_CFG:
                 ^
  symbol:   variable msg_uavionix_adsb_out_cfg
  location: class MAVLinkPacket
/home/wickedshell/code/SwiftGCS/src/java/com/MAVLink/MAVLinkPacket.java:923: error: cannot find symbol
                return new msg_uavionix_adsb_out_cfg(this);
                           ^
  symbol:   class msg_uavionix_adsb_out_cfg
  location: class MAVLinkPacket
/home/wickedshell/code/SwiftGCS/src/java/com/MAVLink/MAVLinkPacket.java:925: error: cannot find symbol
            case msg_uavionix_adsb_out_dynamic.MAVLINK_MSG_ID_UAVIONIX_ADSB_OUT_DYNAMIC:
                 ^
  symbol:   variable msg_uavionix_adsb_out_dynamic
  location: class MAVLinkPacket
/home/wickedshell/code/SwiftGCS/src/java/com/MAVLink/MAVLinkPacket.java:926: error: cannot find symbol
                return new msg_uavionix_adsb_out_dynamic(this);
                           ^
  symbol:   class msg_uavionix_adsb_out_dynamic
  location: class MAVLinkPacket
/home/wickedshell/code/SwiftGCS/src/java/com/MAVLink/MAVLinkPacket.java:928: error: cannot find symbol
            case msg_uavionix_adsb_transceiver_health_report.MAVLINK_MSG_ID_UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT:
                 ^
  symbol:   variable msg_uavionix_adsb_transceiver_health_report
  location: class MAVLinkPacket
/home/wickedshell/code/SwiftGCS/src/java/com/MAVLink/MAVLinkPacket.java:929: error: cannot find symbol
                return new msg_uavionix_adsb_transceiver_health_report(this);
                           ^
  symbol:   class msg_uavionix_adsb_transceiver_health_report
  location: class MAVLinkPacket
```

**Comment by julianoes** [comment]
Does anyone know how I could reproduce this? I'm lost and I would like to get this in.

**Comment by WickedShell** [comment]
@julianoes Sorry, I'm traveling at the moment and hadn't had a chance yet to sort out the commands to build it from outside of a leiningen project. I'll be back in a couple of days (weather permitting) and will be able to test the commands at that point. In the interim the following comments might help you reproduce it:

As far as generation was concerned I was building by just using the GUI tool for generating the java files. After you have done that they need to be located in a folder called `com/MAVLink` (ideally generation should do this for you, but it doesn't which isn't hard to fix). From there you might be able to just call `javac` with all the files generated being passed in. But I wasn't sure yet if that would work or not. (My use case keeps dropping them into a different build system and just letting it fail to compile).

**Comment by WickedShell** [comment]
@julianoes:

1. Checkout PR, update submodules
2. Run the `mavgeneate.py` script from the mavlink dir
3. Select the `ardupilotmega.xml` for XML
4. Set an our directory
5. Set language java
6. Set protocol 2.0
7. Generate
8. Make a `com/MAVLink` folder and move all the output java files into it
9. Run the java compiler against all the files in those subfolders. `javac com/MAVLink/*java com/MAVLink/*/*java`

```
wickedshell@milton ~ % mkdir tmp
wickedshell@milton ~ % cd tmp 
wickedshell@milton ~/tmp % ls 
ardupilotmega  enums               Messages     uAvionix
common         MAVLinkPacket.java  Parser.java
wickedshell@milton ~/tmp % mkdir -p com/MAVLink
wickedshell@milton ~/tmp % mv * com/MAVLink 
mv: cannot move 'com' to a subdirectory of itself, 'com/MAVLink/com'
wickedshell@milton ~/tmp % javac com/MAVLink/*java com/MAVLink/*/*java
com/MAVLink/MAVLinkPacket.java:922: error: cannot find symbol
            case msg_uavionix_adsb_out_cfg.MAVLINK_MSG_ID_UAVIONIX_ADSB_OUT_CFG:
                 ^
  symbol:   variable msg_uavionix_adsb_out_cfg
  location: class MAVLinkPacket
com/MAVLink/MAVLinkPacket.java:923: error: cannot find symbol
                return new msg_uavionix_adsb_out_cfg(this);
                           ^
  symbol:   class msg_uavionix_adsb_out_cfg
  location: class MAVLinkPacket
com/MAVLink/MAVLinkPacket.java:925: error: cannot find symbol
            case msg_uavionix_adsb_out_dynamic.MAVLINK_MSG_ID_UAVIONIX_ADSB_OUT_DYNAMIC:
                 ^
  symbol:   variable msg_uavionix_adsb_out_dynamic
  location: class MAVLinkPacket
com/MAVLink/MAVLinkPacket.java:926: error: cannot find symbol
                return new msg_uavionix_adsb_out_dynamic(this);
                           ^
  symbol:   class msg_uavionix_adsb_out_dynamic
  location: class MAVLinkPacket
com/MAVLink/MAVLinkPacket.java:928: error: cannot find symbol
            case msg_uavionix_adsb_transceiver_health_report.MAVLINK_MSG_ID_UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT:
                 ^
  symbol:   variable msg_uavionix_adsb_transceiver_health_report
  location: class MAVLinkPacket
com/MAVLink/MAVLinkPacket.java:929: error: cannot find symbol
                return new msg_uavionix_adsb_transceiver_health_report(this);
                           ^
  symbol:   class msg_uavionix_adsb_transceiver_health_report
  location: class MAVLinkPacket
6 errors
```

**Comment by magicrub** [comment]
Those adsb msgs are from another xml that gets imported into ardumega. The ardumega includes common and the uAvionoix. It might be that the Java parser can not include/import two files, just one. I recall there was some tiny change we did to the c parser to do that.

**Comment by WickedShell** [comment]
@magicrub Yes, as noted above https://github.com/ArduPilot/pymavlink/pull/122 should be fine, but this PR needs to be rebased to incorporate the changes before it can really be tested.

**Comment by julianoes** [comment]
@WickedShell thanks for the steps.

I'm trying to get the two pymavlink forks in sync, see: https://github.com/ArduPilot/pymavlink/pull/132.

**Comment by Hunter522** [comment]
@julianoes  and @WickedShell RE the problems importing dialect message definitions.

I ran into same issues since I needed the ADSB messages from uAvionix.xml. My Java Mavlink2 implementation over at https://github.com/ArduPilot/pymavlink/pull/127 fixes this issue. I think the fix is entirely in `mavgen_java.py`.

**Comment by WickedShell** [comment]
@Hunter522 I somehow missed that MAVLink2 impl. Will review it later today.

**Comment by LorenzMeier** [comment]
Is there an update here?

**Comment by julianoes** [comment]
@LorenzMeier we need to merge/sync the mavlink/pymavlink fork and clean up the current disconnected state, see: https://github.com/ArduPilot/pymavlink/pull/132

**Comment by amilcarlucas** [comment]
pymavlink is now in sync with upstream. The title in this PR is very missleading. #826 already updates the pymavlink submodule. Please change the PR title

**Pull request closed without merging**
