### PR TITLE
common.xml: remove wip from AIS_VESSEL

### PR DESCRIPTION
**Pull request by peterbarker**
This one has cooked long enough...

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @peterbarker 

There are also a whole bunch of enums associated with this -e.g. `AIS_FLAGS` that have informal wip markup - you can see them in https://github.com/mavlink/mavlink/pull/1228

I'll make sure there are no objections in dev call tonight.

**Comment by hamishwillee** [comment]
From devcall - we're trying to stick with the governance model proposal of only "formally" including things in common.xml that are in one stack and with "firm intent" to get in another stack. We think this fits that model - just trying to confirm that this either is or will be supported by MAVSDK as well in the near future. @julianoes @bazfp - can you confirm?

**Comment by peterbarker** [comment]
> From devcall - we're trying to stick with the governance model proposal of only "formally" including things in common.xml that are in one stack and with "firm intent" to get in another stack. We think this fits that model - just trying to confirm that this either 

Fair enough.  As an alternative we could move it into `ardupilotmega.xml`.

**Comment by hamishwillee** [comment]
@julianoes @bazfp - can you confirm https://github.com/mavlink/mavlink/pull/1817#issuecomment-1073507739

Thanks @peterbarker - I think would be good to get into common, we're just trying to 'do the right thing". Either way though, this can't be merged until the associated enums are also updated to remove the "Wip comments".

**Comment by bazfp** [comment]
> From devcall - we're trying to stick with the governance model proposal of only "formally" including things in common.xml that are in one stack and with "firm intent" to get in another stack. We think this fits that model - just trying to confirm that this either is or will be supported by MAVSDK as well in the near future. @julianoes @bazfp - can you confirm?

I have firm intent to get USV features like AIS features into our autonomy + MAVSDK

**Comment by hamishwillee** [comment]
Thanks @bazfp - sounds great. FMI, any timeframe in mind?

@auturgy You OK to merge? This is good enough for me.

**Review by hamishwillee — APPROVED** [review]

**Comment by bazfp** [comment]
> Thanks @bazfp - sounds great. FMI, any timeframe in mind?

AIS is below some more crucial changes, but may jump up as we have discussed including this on a recent vehicle

**Comment by auturgy** [comment]
> merge

Yup

**Review by hamishwillee — APPROVED** [review]
Agreed merge in devcall based on normal rule of "in one stack" and commitment to get in another.

**Pull request merged**
