### PR TITLE
Add MAV_CMD for starting/stopping high latency telemetry

### PR DESCRIPTION
**Pull request by acfloria**
Adds the interface to request starting/stopping the high latency telemetry on the autopilot.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This is more @dogmaphobic since he is implementing the switching part.

**Comment by acfloria** [comment]
What is the status here? Good to merge or are changes required?

**Comment by dagar** [comment]
I'm good with this if Gus is. 
@acfloria github won't let me merge unless you rebase.

**Comment by dogmaphobic** [comment]
When would you need this? Also, couldn't it be consolidated into one CONTROL command and have an argument for on/off?

**Comment by acfloria** [comment]
I would use this to command the vehicle to turn high latency on/off. But sure it can be incorporated to one command. I just followed the example of `MAV_CMD_LOGGING_START`/`MAV_CMD_LOGGING_STOP`

**Pull request merged**
