### PR TITLE
ardupilotmega.xml: add AUTOPILOT_VERSION_REQUEST message

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by geeksville** [comment]
Hi @tridge does this change look okay to you?  I'd like a 3dr project to be based on master as much as possible so eager to get this change in.

**Comment by tridge** [comment]
applied, thanks!

**Comment by LorenzMeier** [comment]
Actually

**Comment by LorenzMeier** [comment]
Now that I'm looking at it, why can't this simply be a command enum entry?

**Comment by LorenzMeier** [comment]
How about:
```
<entry value="500" name="MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES">
                    <description>Request autopilot capabilities</description>
                    <param index="1">1: Request autopilot version</param>
                    <param index="2">Reserved (all remaining params)</param>
               </entry>
```
This has the upside of common command handling, command acks and command retransmission all handled by existing command handling code.

**Comment by tridge** [comment]
good idea. i've added MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES
I'll remove the ardupilotmega.xml one when I am sure all users have updated

**Comment by jschall** [comment]
Sounds like I can close this.

**Pull request closed without merging**
