### PR TITLE
Add xml formatting check to travis and run xmllint on message definitions.

### PR DESCRIPTION
**Pull request by jgoppert**
This keeps the xml tidy and makes travis fail if it needs formatting.

This is a result of me trying to open up the xml in vi and having all of the indenting off by one from standard, which annoyed me.

If this goes in, any old PR's would need to rebase and run scripts/xml_format.sh on their PR.

@LorenzMeier  @tridge Can you weigh in on this? I want to make sure this seems reasonable to you.

### CODE REVIEW

**Comment by jgoppert** [comment]
@magicrub That is how xmlpretty was setup, to sort the keys. We can modify xmlpretty to force type first if we want.

**Comment by magicrub** [comment]
Thanks. I don't know if it's a good/bad idea, just wondering. Makes sense to have the name first though.

**Comment by tridge** [comment]
thanks! 
how hard is it to make xmlpretty use the ordering we have used up to now? I'd like that to minimise the diff

**Comment by jgoppert** [comment]
I will take a look. Shouldn't be too hard. I can use xmllint if necessary.

**Comment by jgoppert** [comment]
@tridge It was pretty painful with lxml/ xml (http://stackoverflow.com/questions/2741480/can-elementtree-be-told-to-preserve-the-order-of-attributes). I switched it to xmllint and it preserves order.

**Comment by jgoppert** [comment]
@tridge @LorenzMeier okay for merge?

**Comment by tridge** [comment]
looks great, thanks!

**Pull request merged**
