### PR TITLE
Use copter mode mappings for ArduSub

### PR DESCRIPTION
**Pull request by jaxxzer**
This allows mavproxy to be used with ArduSub

### CODE REVIEW

**Comment by rmackay9** [comment]
nifty.  like to see ardusub making it's way towards master

**Comment by magicrub** [comment]
I think there are some white space problems with this that wound be nice to
clean up.

**Comment by LorenzMeier** [comment]
@jaxxzer Can you fix the whitespace here?

**Comment by jaxxzer** [comment]
Sure thing.

**Comment by LorenzMeier** [comment]
Ehm - now the whole file is full of whitespace changes. Could you please only apply the relevant changes?

**Comment by jaxxzer** [comment]
Oh, wow, I see what you meant now. Sorry.

**Comment by rmackay9** [comment]
can we pull this in now?

**Comment by LorenzMeier** [comment]
This moved since into another repo, closing.

**Pull request closed without merging**
