### PR TITLE
Altitude report including all the various estimates used in the system.

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tridge @rmackay9 @DonLakeFlyer @dogmaphobic This massive altitude report reconciles the different altitude estimates we have. Please provide feedback.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
In particular wondering if we need variances here, in particular for the distance sensors.

**Comment by rmackay9** [comment]
I can see how you have all these altitudes because we've run into them in ardupilot as well.  My counter proposal though is that we only need to send the terrain alt because all the other altitudes are sent in other messages or can be calculated using other messages.

altitude_monotonic - I think this is very close to the alt-above-EKF-origin which can be calculated from the absolute alt and the GPS_GLOBAL_ORIGIN's alt.  If it's not the same as the alt-above-EKF-origin I wonder what value it's adding when we already have alt-above-ekf-origin, absolute alt and alt-above-home.

altitude_amsl - sending this is good but isn't it already included in the GLOBAL_POSITION_INT?

altitude_local - this is the alt-above-ekf-origin so could be calculated from the origin-alt (sent in the GPS_GLOBAL_ORIGIN message) and the above altitude_amsl.

altitude_terrain - sending this is good and I don't think we report it anywhere else.

bottom_clearance - this looks like the same as the DISTANCE_SENSOR

**Comment by LorenzMeier** [comment]
One thing to keep in mind is the complexity involved in "calculating from other altitudes". If those messages are streaming its fine, but if they are stateful it becomes very challenging to get things right.

**Comment by LorenzMeier** [comment]
Closing in favour of combined control_state PR.

**Pull request closed without merging**
