### PR TITLE
Loiter commands param4 to offer flexible exit xtrack option for fixed wing

### PR DESCRIPTION
**Pull request by magicrub**
When exiting a loiter in fixed wing it is sometimes nice to have flexible exit options. This PR uses param4 field for fixed wing as flag to the mission item that allows either:

- follow the path from center of loiter waypoint to next waypoint (0)
- follow the path from tangent exit point to next waypoint (1)

loiter_exit_xtrack

Current use of param4 is "Desired yaw angle" which does not make any sense for a fixed wing forward-flying type aircraft.

Pending PR in ArduPilot https://github.com/ArduPilot/ardupilot/pull/3750 to utilize this

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tridge Makes sense, please merge if you agree.

**Comment by magicrub** [comment]
bump @tridge

**Comment by tridge** [comment]
applied, thanks!

**Comment by DonLakeFlyer** [comment]
@magicrub What are the units for yaw angle? Degrees or Radians?

**Comment by magicrub** [comment]
Unknown, they were there before me. I'll Check to see if apm is even using
it

**Comment by DonLakeFlyer** [comment]
@magicrub Any update on this?

**Comment by magicrub** [comment]
Only Plane is using that param for that packet.

**Comment by DonLakeFlyer** [comment]
Units?

**Comment by magicrub** [comment]
I don't know, there's nothing there in ArduPilot taking advantage of it.
How about in PX4?

**Comment by dagar** [comment]
I was going to implement this for PX4 fixed wing.

**Comment by magicrub** [comment]
<hi-5>

**Pull request closed without merging**
