### PR TITLE
common.xml: Camera definition files should support xz compression

### PR DESCRIPTION
**Pull request by hamishwillee**
The component and camera definition files may be compressed using .xz, and GCS that implement the protocol must support this. Already covered in other docs, e.g.  https://mavlink.io/en/services/component_def.html#file-compression

Fixes https://github.com/mavlink/mavlink/issues/1275

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dogmaphobic There is a big discussion of this in https://github.com/mavlink/mavlink/issues/1275 - essentially this expects the GCS to note the .xml.gz extension and decrypt the text file. Saves quite a bit of flash space.

**Comment by hamishwillee** [comment]
@dogmaphobic Can you confirm this is correct please - ie that QGC supports automatic extraction of a camera definition file with extension .xml.gz ?

**Comment by hamishwillee** [comment]
@julianoes @LorenzMeier We will support **.xz** compressed component information files. However according to Gus it is NOT the case that QGC supports compressed *camera* information files (as this PR says ".xml.gz"). 

What's the best way forward?
- Close this (no requirement)
- Modify compression required to **.xz** and merge, even though QGC does not support it.
- As above, but someone gets allocated to making QGC support it
- Someone works to move the camera definition files and schema into component information format?
- Turn this into an issue - we'd like to do this at some point. I have no problem leaving desirable issues open, but would prefer that PRs were closed.

**Comment by julianoes** [comment]
MAVSDK does not support `.xz` yet but it can easily be added once required.

**Comment by hamishwillee** [comment]
> MAVSDK does not support .xz yet but it can easily be added once required.

@julianoes True, but when is something "required"? I'd say that this is "shortly after I submit this", which means that I shouldn't do this until you or someone else has volunteered to make that change, and ideally prototyped it. Volunteering? :-)

**Comment by julianoes** [comment]
I'll add it as soon as someone complains that their .xz file doesn't work :smile:. It's called just-in-time-driven-programming :smile:

**Comment by hamishwillee** [comment]
Hmmm. Well, I'll hit merge, but QGC is now non compliant with this boo hiss

**Pull request merged**
