### PR TITLE
HOME POSITION: Implement proper messaging support to query and set th…

### PR DESCRIPTION
**Pull request by LorenzMeier**
…e home position

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tridge @rmackay9 Would be good to discuss this. This is based on a discussion with Randy the other week.

**Comment by rmackay9** [comment]
I think having this message would be great.  The format looks good to me although I think the approach fields are a separate concept that should be moved to another message.

**Comment by LorenzMeier** [comment]
In master - need separate messages for approach planning.

**Comment by rmackay9** [comment]
Great.  By the way, I've been thinking a bit about the home position stored in the mission as waypoint 1 and a transition plan might involve using a capabilities bit.

**Comment by LorenzMeier** [comment]
That makes perfect sense. We should add the home position to the bitfield enum, and its fantastic to hear you have a transition plan in mind. I'm really, really personally delighted that we're gaining momentum and working closely together to make the MAVLink experience more smooth. Rock on!

**Pull request closed without merging**
