### PR TITLE
Added the LOCAL_LATCHED_NED to the MAV_FRAME enum.

### PR DESCRIPTION
**Pull request by Susurrus**
I didn't know if this should also be added to MAVLink 0.9.

I find this is commonly something I want to do, where I want things defined in the local frame, but I want all of the positions to be relative to the vehicle position when it received the messages. This is because often when I'm out there's traffic or other obstacles I need to avoid. Because of this, my starting location may move, but I still want the relative pattern to be preserved.

### CODE REVIEW

**Comment by tridge** [comment]
what implementations use LOCAL_OFFSET_NED now? I would have thought that latching would always be done if you implement that frame.

**Comment by Susurrus** [comment]
My implementation originally used `LOCAL_OFFSET_NED` for this purpose, but from discussions with Lorenz, it sounded like that was incorrect and ALL frames should only be evaluated when the mission item is reached NOT when the mission items are received. This is why I added a new frame instead of (ab)using `LOCAL_OFFSET_NED`.

**Comment by Susurrus** [comment]
@tridge @LorenzMeier Can I get a consensus if this is suitable for merging when I fix up the commit or is this not something you want to merge?

**Comment by mairsbw** [comment]
I'd like to get this resolved one way or another. Pinging @tridge and @LorenzMeier.

**Comment by LorenzMeier** [comment]
@mairsbw It did get ignored because it failed the build. Can you rebase?

**Comment by mairsbw** [comment]
Looking at the build failure, I think it was a Travis failure, not this commit.

**Comment by mairsbw** [comment]
Can you re-run the build Lorenz? This change doesn't have merge problems or introduce anything that would break the build.

**Comment by mairsbw** [comment]
@LorenzMeier Looks like the checks pass now.

**Comment by Susurrus** [comment]
I no longer need this and there doesn't seem like there's any need from the community, so closing this.

**Pull request closed without merging**
