### PR TITLE
[Proposal] Delete possibly unused cmake tree

### PR DESCRIPTION
**Pull request by hamishwillee**
This is a **proposal** to delete the cmake tree https://github.com/mavlink/mavlink/tree/master/cmake which is undocumented and appears to not have been touched since 2014.

I don't know what it is for, so I am using this mechanism to get feedback so it can either be documented or deleted.

@jgoppert @tridge You both touched this - any idea what it is for/whether it is used by anyone?

### CODE REVIEW

**Comment by hamishwillee** [comment]
This was discussed in the dev call. We've had no signal from @jgoppert that is has value. The strong feeling is that this probably isn't used. Therefore the decision was to merge this PR. It can be reverted if we are wrong, and we'll at least then have an understanding of its value.

**Comment by AspenEyers** [comment]
Looks like this change broke my build... :/ 

```
CMake Deprecation Warning at CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at CMakeLists.txt:32 (include):
  include could not find requested file:

    DefineCMakeDefaults


CMake Error at CMakeLists.txt:41 (include):
  include could not find requested file:

    ExternalProjectWithFilename


** Finding libraries
-- mavgen_EXECUTABLE: /usr/local/bin/cmake;-E;env;PYTHONPATH=:/media/aspen/D1/opt/mavlink;/usr/bin/python3.6;-m;pymavlink.tools.mavgen
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/ASLUAV.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/ardupilotmega.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/common.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/matrixpilot.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/minimal.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/paparazzi.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/python_array_test.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/test.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/ualberta.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/ASLUAV.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/ardupilotmega.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/common.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/matrixpilot.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/minimal.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/paparazzi.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/python_array_test.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/test.xml
-- processing: /media/aspen/D1/opt/mavlink/message_definitions/v1.0/ualberta.xml
CMake Error at /usr/local/share/cmake-3.20/Modules/CPack.cmake:626 (message):
  CPack welcome resource file:
  "/media/aspen/D1/opt/mavlink/cmake/WELCOME.txt" could not be found.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/CPack.cmake:633 (cpack_check_file_exists)
  CMakeLists.txt:242 (include)


-- Configuring incomplete, errors occurred!
See also "/media/aspen/D1/opt/mavlink/build/CMakeFiles/CMakeOutput.log".
```

include(DefineCMakeDefaults)
Used in line 32 of `mavlink/CMakeLists.txt`

include(ExternalProjectWithFilename)
Used in line 41 of `mavlink/CMakeLists.txt`

set(CPACK_RESOURCE_FILE_WELCOME "${MAVLINK_SOURCE_DIR}/cmake/WELCOME.txt")
Used in line 234 `mavlink/CMakeLists.txt`

**Comment by hamishwillee** [comment]
Sorry to hear that. Can you tell me what purpose this serves then, and how it is used? How did you find out about it?

**Comment by AspenEyers** [comment]
Hi, I found out about it this morning accidentally when running a system build in a docker container that includes and builds mavlink as one of its components.
I can't say I know anything about these files in particular, only that they are still a part of the mavlink CMakeLists.txt which can no longer find them.

The steps followed to reproduce the issue are as follows:
```
git clone https://github.com/mavlink/mavlink.git
cd mavlink && mkdir build && cd build 
cmake .. 
```

What other information would be useful for you?

**Comment by julianoes** [comment]
Well, I guess we should revert the change. I wasn't aware of the fact that there is a CMakeLists.txt. Clearly it's something that can be used, and is used.

**Comment by hamishwillee** [comment]
Change reverted - thanks @julianoes . Julian, so does this mean "building MAVLink as its own library"? Basically if I was to explain this file tree, what is it's point?

**Comment by julianoes** [comment]
I don't know what it does.

**Pull request merged**
