### PR TITLE
MAV_CMD_REQUEST_CAMERA_IMAGE_CAPTURE: clarify param4 values

### PR DESCRIPTION
**Pull request by hamishwillee**
QGC is using NaN rather than 0 to indicate "not valid" in [MAV_CMD_IMAGE_START_CAPTURE.param4](https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE) (sequence number) when param3 != 1. This works with PX4 and as it is clearly an invalid value I would expect a system getting this to handle it. 

What this change does is explicitly allow the NaN case. 

I also took opportunity to mark up the other parameters as reserved with an NaN value using the expected syntax.

### CODE REVIEW

**Comment by hamishwillee** [comment]
From Don

> I'm guessing when param3 == 1 px4 firmware will puke on param4 = NaN to ignore instead of 0. Hmm, which in turn I think means QGC should really be changed. Otherwise the spec just gets too polluted. The spec should probably update to say somehow 0 is used to not only specify no camera sequence number specified but also used when param4 is not used at all.

**Comment by hamishwillee** [comment]
@DonLakeFlyer 

>  I'm guessing when param3 == 1 px4 firmware will puke on param4 = NaN to ignore instead of 0. Hmm, which in turn I think means QGC should really be changed. Otherwise the spec just gets too polluted. The spec should probably update to say somehow 0 is used to not only specify no camera sequence number specified but also used when param4 is not used at all.

And so it should - **either** NaN or 0 are invalid if param3 ==1. 

Even so, I've modified to say "always set to zero unless `param3 == 1`. If you're not happy with this, propose a change.

```
<param index="4" label="Sequence Number" minValue="1" increment="1">
Capture sequence number starting from 1. This is only valid for single-capture (param3 == 1), otherwise set to 0. 
Increment the capture ID for each capture command to prevent double captures when a command is re-transmitted.</param>
```

**Comment by DonLakeFlyer** [comment]
I think that's good. Thanks @hamishwillee

**Comment by hamishwillee** [comment]
Self merging. This does not change the meaning, just clarifies the value.

**Pull request merged**
