### PR TITLE
Dataflash mavlink

### PR DESCRIPTION
**Pull request by peterbarker**
See also https://github.com/mavlink/mavlink/pull/397

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Could you please provide the complete protocol description similar to what has been provided for waypoints here?
http://qgroundcontrol.org/mavlink/waypoint_protocol

We need to stop adding sub protocols without ever documenting them and I would very much appreciate if you could lend a hand in breaking this negative pattern. It would also be worthwhile to consider if this is really a logging thing or a general file streaming thing.

The next thing we will need to do is to stream ESC firmware for upgraded via CAN bus in the other direction. Can we maybe achieve this with this protocol as well?

**Comment by LorenzMeier** [comment]
@peterbarker Could you provide feedback on the documentation plans for this? @tridge FYI

**Comment by tridge** [comment]
applied, thanks!

**Comment by magicrub** [comment]
@tridge looks like this never made it in.

**Pull request closed without merging**
