### PR TITLE
Add MAV_CMD_SELECT_TRIGG_CAM command.

### PR DESCRIPTION
**Pull request by MatejFranceskin**
MAV_CMD_SELECT_TRIGG_CAM as a mission item added to the mission plan selects the camera and stream that will be used for capturing images in case where the vehicle has multiple cameras and/or camera has multiple sensors available.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Sounds sensible but I'll have a proper look tomorrow. The things I'm interested in checking/questioning are (and you might want to clarify, but you might not since it is a stream of muddy thinking ...):
- Whether this can be used as a command as well
- Confirming whether this applies for the next call on the camera, or all subsequent calls on the camera. Does it outlast the mission. So normally you might use this as a command to set the default behaviour and as a mission item to override the default behaviour.
- Will I ever want to trigger 2 but not all cameras - ie. this can trigger all and just one, but not necessarily specific ones.
- Is there any other camera triggering that this might clash with, in which case how is that resolved.
- Does/should this select anything for video as well? 
- Is there any overriding that can happen from commands etc during mission, and is there any conflict resolution.
- Is there any other configuration that you might want to do in a mission other than triggering - let's think about that quickly now.

**Comment by MatejFranceskin** [comment]
1. MAV_CMD_SELECT_TRIGG_CAM is used as command as well. When it is reached in the mission the flight controller sends the same command to all cameras. This is because also those that are not addressed have to "unselect" itself.
2. Yes, the command outlasts the mission.
3. The way it is currently designed we can trigger only one or all the cameras.
For other questions, we have to discuss it. In current implementation this command selects the camera for all commands that are related to camera triggering not just f.e. MAV_CMD_IMAGE_START_CAPTURE but also MAV_CMD_DO_SET_CAM_TRIGG_DIST and others. It could be extended also to MAV_CMD_VIDEO_START_CAPTURE which already contains information about which stream to record but if used as part of the mission plan then it doesn't address particular camera.

**Comment by hamishwillee** [comment]
Thanks @MatejFranceskin ! There is a dev call this evening (my time tonight) if you want to come and discuss. Julian is on holiday and I'm not sure who will show up. Here are my thoughts anyway.

As I understand it, when the autopilot executes this command it would broadcast the message to all cameras (vehicle system ID and component id =0). Each camera on the vehicle gets the message and checks whether it has a component id that matches the message (and stream ID). If it does, then it sets it's state to either ignore or accept future broadcast camera commands [the _ignore_ is the interesting case, since presumably by default a camera will accept any broadcast command].
It will ignore further commands until it gets a new command to enable itself (should it persist the setting across reboots?)

Is that about right?

I think I prefer a design where  - ie the vehicle reverts to the user's preferences for normal flight. However as specified I'm not sure you can do that.

My first concern is what the GCS/user should do for cameras that were set disabled in the mission.

For example, in the current model when flying _outside_ of a mission the GCS allows you to switch between cameras, and commands are directed to the current camera.
- If the current camera was disabled by the mission, should it be shown as active in the UI?
- What should a disabled camera do if it gets a camera trigger command later that is targeted to its component ID (not broadcast)? Should it decide it is still disabled, or should it accept the command? 
- If it can't act on commands, then I THINK that we need to expose the enabled/disabled state of the cameras to the GCS. 

My second concern is about the next mission. Say I run a mission and it sets the camera up. I then run a new mission and it does nothing with cameras - it just users whatever is currently set. 
Generally it is much better if a setting in a mission does not persist beyond the mission. 

Lastly, I wonder if the mission should in some way display which cameras are active and which are inactive? 

Do we perhaps need to have a camera enabled/disabled state and publish that as well?

Lots of questions sorry.

**Comment by auturgy** [comment]
https://github.com/mavlink/mavlink/issues/1678

**Comment by hamishwillee** [comment]
THanks for closing this @MatejFranceskin 

I don't think it is a solved problem yet. If we ever need to then I think we'd lean towards the gimbal approach and just add a target component id to an empty param (like [MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE)) and get the flight stack or mavlink camera to use this if it is non-zero.
Not "perfect" but consistent.

**Pull request closed without merging**
