### PR TITLE
Common: Add a stage option to EXTENDED_SYS_STATE

### PR DESCRIPTION
**Pull request by WickedShell**
This replaces #684, allows autopilots to report custom internal stages associated with a flight mode.

### CODE REVIEW

**Comment by WickedShell** [comment]
@LorenzMeier @DonLakeFlyer @dagar are you guys good with this?

**Comment by dagar** [comment]
I personally think it's a step in the wrong direction, but if you believe it's the best solution to your problem I won't object.

**Comment by DonLakeFlyer** [comment]
My only comment is that it would seem to belong here. Whether it is a good thing or now I have no opinion.

**Comment by WickedShell** [comment]
I'm strongly of the opinion that it's the best approach at this point, or any proposed alternative to date. The only other solution would be to have a very long list of enums, much the way we have CMD's that each project can update as needed, but every GCS would quickly get into the stage of having to interpret the modes differently based on what autopilot they are talking to.

**Comment by mhkabir** [comment]
I've added this to https://github.com/mavlink/mavlink/pull/727.

**Pull request closed without merging**
