### PR TITLE
New px4modes

### PR DESCRIPTION
**Pull request by squilter**
Dronekit mode changes should be working again with this PR.

Closes #612

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@hamishwillee Could you give this a quick test to make sure it doesn't disrupt your workflow?

**Comment by hamishwillee** [comment]
Er, for DK-Python? @mrpollo or @peterbarker want to do this?

**Comment by peterbarker** [comment]
Doesn't seem to kill the pymavlink tools.

dk-python can connect.  Much better :-)

@hamishwillee really? :-)

**Comment by hamishwillee** [comment]
@peterbarker Yes really - @LorenzMeier would be better much better chasing you for this in the first place :-)

**Comment by mrpollo** [comment]
hey @peterbarker how did you test this?

**Comment by peterbarker** [comment]
On Tue, 23 Aug 2016, Ramon Roche wrote:

> hey @peterbarker how did you test this?

Made sure that once it was installed I could still mavlogdump/MAVExplore.

Made sure I could talk to a PixHawk flashed with ArduPilot and with PX4 
using both MAVProxy and dronekit.

**Comment by LorenzMeier** [comment]
Awesome, thanks everybody! Rebased and applied.

**Comment by mrpollo** [comment]
this went into [dronekit 2.9.0](https://github.com/dronekit/dronekit-python/releases/tag/v2.9.0), thanks all

**Pull request closed without merging**
