### PR TITLE
common.xml: replace the non readable WIP information, with informatio…

### PR DESCRIPTION
**Pull request by amilcarlucas**
…n that pymavlink and documentation generator can use.

this is a continuation of #910

### CODE REVIEW

**Comment by hamishwillee** [comment]
@amilcarlucas A complete aside ...

This was a new tag on me, so I looked it up in the docs. I can see, for example, that we're doing the right thing in the docs and marking these up [MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN](https://mavlink.io/en/messages/common.html#MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN). However it occurs to me that we should probably document at least some of the main tags. I'm not talking a full dtd definition - just a few of the more important or less obvious ones - e.g. extensions, wip. 

What do you think? What tags would we need to cover? 

For this particular case, I would need to know what WIP does for the generated output - anything? What are the semantics - we just don't promise to keep it at any point?

**Comment by hamishwillee** [comment]
As an aside, FMI what is the trigger for changing a WIP into an "accepted" part of the standard?

**Comment by amilcarlucas** [comment]
Remove the `<wip>` element.

**Comment by amilcarlucas** [comment]
@hamishwillee the main discussion is going on #910 

But yes, it does make sense to document the XML elements and their respective attributes.
Can you start something out? I will gladly review it.

**Comment by hamishwillee** [comment]
@amilcarlucas Sure. But I am out of town for a week, so after that.

**Comment by amilcarlucas** [comment]
I will wait for travis to pass the tests and merge it if it does.

**Comment by hamishwillee** [comment]
Failed. I guess we still have to get the change to pymavlink into our branch?

**Comment by amilcarlucas** [comment]
This can be "rebased and merged" as soon as ArduPilot/pymavlink#205 gets merged upstream.

**Comment by hamishwillee** [comment]
Can't wait!

**Comment by amilcarlucas** [comment]
@hamishwillee You should document 'entry', 'enum', 'message' and 'mavlink' elements with their respective attributes

**Comment by hamishwillee** [comment]
@amilcarlucas Yes, it is still very much "WIP", but I have started that in https://github.com/mavlink/mavlink-devguide/pull/96/files

**Pull request merged**
