### PR TITLE
Fix quotes in .xml files

### PR DESCRIPTION
**Pull request by amilcarlucas**
I have another patch that will fix the indentation of the rest of the .xml files so for now just ignore indentation

### CODE REVIEW

**Comment by magicrub** [comment]
What's wrong with the current quotes? Also, you changed the indentation. Please look at the diff.

**Comment by WickedShell** [comment]
As far as I know the only reason to use the &qout; form is when you are using it as an attribute, putting a " in a body like that is absolutely valid.

**Comment by amilcarlucas** [comment]
If " are valid inside a body and do not cause any issues with any of the tools, then this patch makes no sense.
But why are &qout; already in the files ?

**Comment by WickedShell** [comment]
You must escape & everywhere, as it is otherwise a special character.
Escaping "s aren't needed in a body. If you aren't encountering an error or
warning from some tooling I'm curious why you put together the PR without
knowing if it fixed anything?

**Pull request closed without merging**
