### PR TITLE
merge ardupilotmega.xml from ardupilot

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
What is going on that we have no diff here?

**Comment by jschall** [comment]
Its because it is too big a change for github to display - the entire file had formatting software run on it.

**Comment by liamstask** [comment]
is it possible to create separate commits for the formatting and for the merge?

**Comment by jschall** [comment]
Yes but the master version of this file is in ardupilot and this is just
bringing mavlink up to speed.

**Comment by LorenzMeier** [comment]
@jschall the way this works is that MAVLink is maintained and reviewed here. Making PRs unreviewable doesn't fit that process and can lead to bad design and spec drift. Please re-submit with something that is reviewable.

Hint: If you were to contribute a formatting tool and the docs for it (for Linux and Mac OS) we could format all files and enforce a common code style. That way you don't have to re-do your changes by hand and all the other files gain consistent formatting.

**Comment by DonLakeFlyer** [comment]
> Yes but the master version of this file is in ardupilot and this is just

The master version needs to be here, otherwise ground stations will fall out of date.

**Comment by jschall** [comment]
OK. I will make a more incremental PR as I did with the upstream version of the file.

**Comment by jschall** [comment]
Yes, but we wait for changes to get into the ardupilot repository before pushing them here, so that it doesn't become inconsistent with ardupilot.

**Comment by LorenzMeier** [comment]
@jschall To reiterate Don's comment. The *only* authoritative copy of the APM MAVLink specs is in this repository. You cannot keep a community synced on a protocol revision otherwise.

**Comment by LorenzMeier** [comment]
The issue with your process is that you're trying to keep a copy of the file in the autopilot codebase. That's never going to work to keep things in sync, and since you already use GIT submodules you can as well just fix it that way.

**Comment by tridge** [comment]
we will be shortly moving to use a submodule, a PR for that is pending from Sid:
https://github.com/diydrones/ardupilot/pull/3410
note that the submodule will point at our own fork of mavlink, not upstream. We will put changes there first then do PRs against this repo from there.

**Comment by LorenzMeier** [comment]
That makes no sense. A submodule points at a revision, so even with your obsession about controlling your consumed codebases you have that level of control, as it references a single commit. Its just confusing people if you keep tons of forks around.

And it certainly creates drift in technical discussions. PR's against MAVLink specs should go against this repo. You're depriving the community from critical interaction about the right direction in architecture that way, which otherwise would happen naturally through discussions on PRs.

**Comment by tridge** [comment]
it can only point at a revision that exists in the repo. If we want a change and that change hasn't yet been accepted or requires rework but we need it for our release schedule then we need the ability to be able to put what we need in our tree.
Upstream is still the long term master, but we must have the ability to control what code goes into our releases

**Comment by LorenzMeier** [comment]
You have the ability to merge PRs here. I don't see which single benefit you gain from a fork. If you merge something in your fork which is not accepted upstream, you would in fact risk to *deploy* something that is not supported by upstream MAVLink. I don't see why would want to do that.

Again, all you're saying is that you're sacrificing coordination for convenience, and this is clearly not what the idea was in increasing the Dronecode collaboration.

**Comment by jschall** [comment]
here is the updated PR: https://github.com/mavlink/mavlink/pull/494

**Pull request closed without merging**
