### PR TITLE
fix relative import with Python 3

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by tfoote** [comment]
@dirk-thomas this is marked as out of date now

**Comment by dirk-thomas** [comment]
@LorenzMeier This should be a trivial merge. There might be more to do but this is "enough" to at least use it in some scenarios.

**Comment by LorenzMeier** [comment]
Indeed, merged.

**Comment by dirk-thomas** [comment]
Thanks!

**Comment by dirk-thomas** [comment]
Can you maybe release a new version of this package into *Kinetic*? One of our projects relies in this and it would be great to use the official Debian package without requiring patches.

**Pull request merged**
