### PR TITLE
add taget IDs to GIMBAL_DEVICE_ATTITUDE_STATUS

### PR DESCRIPTION
**Pull request by olliw42**
does https://github.com/mavlink/mavlink/issues/1371

### CODE REVIEW

**Comment by julianoes** [comment]
Thanks @olliw42

**Comment by olliw42** [comment]
my pleasure

not sure why the check don't complete

**Comment by olliw42** [comment]
@hamishwillee since merging seems to work again, can this be merged then too? seems to have been approved

**Comment by olliw42** [comment]
@julianoes since you are in merging mood and I've forgotten to ping you too, I'll ping now

:)

**Comment by olliw42** [comment]
fantastic!

many thx!!

**Pull request merged**
