### PR TITLE
add time_boot_ms to GLOBAL_ORIGIN msgs

### PR DESCRIPTION
**Pull request by TSC21**
This allows the companion computer system to properly sync when the global origin changes (for advanced navigation between indoor and outdoor environments).

### CODE REVIEW

**Comment by TSC21** [comment]
@tridge ping

**Comment by LorenzMeier** [comment]
This will break v1.0. Can you please use the proper extend syntax for v2.0?

**Comment by TSC21** [comment]
@LorenzMeier I'm clearly missing something here. What the difference for v2?

**Comment by TSC21** [comment]
@LorenzMeier PR updated.

**Comment by TSC21** [comment]
Can someone of the admins review this PR? Thanks

**Comment by LorenzMeier** [comment]
Can you change that to the full us timestamp instead? Happy to merge then.

**Comment by TSC21** [comment]
Closing in favor of #719

**Pull request closed without merging**
