### PR TITLE
Readme: Updated Mavgen Command line

### PR DESCRIPTION
**Pull request by legonigel**
Corrected mavgen command line syntax.

### CODE REVIEW

**Comment by vooon** [comment]
I think might be useful also add reminder to old mavgen.

Please add to generator.mavgen tail. @tridge please look!
```
if __name__ == __main__:
    raise DeprecationWarning("Executable was moved to pymavlink.tools.mavgen")
```

**Comment by legonigel** [comment]
@vooon @tridge Added the boilderplate to old mavgen.

**Comment by LorenzMeier** [comment]
@legonigel Merged via rebase. We're trying to keep our history tidy, so I fixed up your three commits into a single commit (see master for details).

**Comment by legonigel** [comment]
@LorenzMeier Thanks you.

**Pull request closed without merging**
