### PR TITLE
ardupilotmega: Sync to ArduPilot downstream 28-SEPT-2021

### PR DESCRIPTION
**Pull request by hendjoshsr71**
This PR syncs the upstream version to the ArduPilot downstream.

@amilcarlucas @auturgy

### CODE REVIEW

**Comment by auturgy** [comment]
Thanks Josh

**Comment by davidbuzz** [comment]
Lgtm

**Comment by auturgy** [comment]
I'll wait til the mavlink devcall tonight but expect to merge it then.

**Comment by hamishwillee** [comment]
@auturgy I was within seconds of merging :-). Is there any blocker, or is delay just so you can check it? 

From my perspective an addition by a known stakeholder that passes the test and is approved by a representative of that stakeholder (i.e. you) just gets merged.

**Comment by hamishwillee** [comment]
PS Thanks @hendjoshsr71 !

**Comment by auturgy** [comment]
Or I could do it now.

**Comment by hendjoshsr71** [comment]
Thanks!

**Pull request merged**
