### PR TITLE
common.xml: Do not deprecate MAV_CMD_NAV_FENCE_RETURN_POINT. it is he…

### PR DESCRIPTION
**Pull request by amilcarlucas**
…avily used by Ardupilot

### CODE REVIEW

**Comment by hamishwillee** [comment]
ArduPilot is moving to using the new fence protocol and this makes no sense in the context of the new protocol. We're not proposing that it will be removed, just that it has been superseded by a better alternative.

@auturgy We discuss this one right?

**Comment by amilcarlucas** [comment]
It would be nice to get this one in, ardupilot repo got synced this morning again.
It would be great to minimize the diff.

**Comment by hamishwillee** [comment]
@amilcarlucas Sorry, I missed this :-(. 
I'll discuss with @auturgy this evening.

**Comment by hamishwillee** [comment]
@amilcarlucas Merged - thanks for your patience. I'll update the description in a second issue to make it clear when/how this should be used.

**Pull request merged**
