### PR TITLE
move MAV_CMD_DO_MOTOR_TEST to common

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by magicrub** [comment]
I'd love to move way more than this on another PR.

**Comment by dagar** [comment]
Do you want to open an issue to discuss @magicrub?

Care to review/merge this one?

**Comment by magicrub** [comment]
Looks good to me but on this repo I am a peon like you. Need someone with some authority.

Meanwhile... yes. Let's start an issue with a list of commands to bring over here.

**Comment by DonLakeFlyer** [comment]
Looks good to me as well.

**Pull request merged**
