### PR TITLE
common: HIGH_LATENCY2 is not in WIP anymore

### PR DESCRIPTION
**Pull request by patrickelectric**
HIGH_LATENCY2 WIP issue is closed
Ref: https://github.com/mavlink/mavlink/issues/831#issuecomment-490351685

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by hamishwillee** [comment]
Been around for a while and this is implemented in a few places. So unless the message is seen as seriously flawed I'm happy with this. Any objections @auturgy @julianoes ?

**Comment by auturgy** [comment]
Fine by me

Regards,

James

**Comment by patrickelectric** [comment]
@hamishwillee should we wait @julianoes ?

**Comment by hamishwillee** [comment]
Thanks!

**Comment by patrickelectric** [comment]
Thanks you everybody!

**Pull request merged**
