### PR TITLE
Mavmission update

### PR DESCRIPTION
**Pull request by Susurrus**
As it stands `mavmission.py` doesn't work for my use case. I've updated it in a general way that should work for everyone, with the caveat that support for the `CMD` message has been removed. This message doesn't exist in any message definition file in the repository, so support for it should be removed and the old user of this message (if there are still any) can instead modify this script for their own use. Note that this was done in order to enable outputting multiple mission sets per log file.

### CODE REVIEW

**Comment by tridge** [comment]
The CMD message is for ArduPilot dataflash logs. I find it very useful to extract missions from DF logs for plane and copter.

**Comment by Susurrus** [comment]
@tridge Where's the CMD message documented then? I'll re-add support for it if I can get docs.

**Comment by tridge** [comment]
The DF log format is self-describing. The code that generates the CMD msg is here:
https://github.com/diydrones/ardupilot/blob/master/libraries/DataFlash/LogFile.cpp#L1051
format is here:
https://github.com/diydrones/ardupilot/blob/master/libraries/DataFlash/DataFlash.h#L546
I think it is best to just restore the old CMD handling code

**Comment by Susurrus** [comment]
Done.

**Comment by mairsbw** [comment]
Any other comments on this @tridge?

**Comment by LorenzMeier** [comment]
Could you rebase against master?

**Comment by mairsbw** [comment]
@LorenzMeier I've rebased and merged everything into 1 commit. Can you check this out and either merge this or reject it?

**Comment by peterbarker** [comment]
@mairsbw Are you still interested in getting this into pymavlink?

Looking at this has pointed out a few issues with the current mavmission.py which need addressing, but I don't want to conflict with these patches if you still want to get them in!

I do have some queries about the patch.

**Comment by Susurrus** [comment]
@peterbarker I can help in whatever you need to get this upstreamed? Note that I no longer use MAVLink and do not need this feature implemented, but I'm happy to help get this merged if it helps others.

**Comment by peterbarker** [comment]
On Mon, 19 Sep 2016, Susurrus wrote:

> @peterbarker I can help in whatever you need to get this upstreamed? Note
> that I no longer use MAVLink and do not need this feature implemented, but
> I'm happy to help get this merged if it helps others.

A few questions - and a few musings.

  - Why the waypoint manager?  Would it be possible to instead implement a 
"save_kml" method on the existing wploader object instead?
  - changing the default behaviour (emitting mission.txt) is interesting. 
I can't see a sensible way of retaining the old behaviour, unless we were 
to use "mission.txt" then "mission-1.txt".
  - it would be awesome if we could take a mavlink log and extract both the 
mission and the course flown, and pack it into the one KML file.  We have 
the "mavkml.py" script which extracts flight paths but not missions. 
Perhaps it would be better to have the functionality added to mavkml 
rather than mavmission.py (which is usually used to extract a mission in a 
form that can then be uploaded to a vehicle)?

**Comment by Susurrus** [comment]
>   - Why the waypoint manager?  Would it be possible to instead implement a 
> "save_kml" method on the existing wploader object instead?

I can't think of a reason why that would be a bad way to do it, but I'm not too familiar with the wploader object anymore.

>   - changing the default behaviour (emitting mission.txt) is interesting. 
> I can't see a sensible way of retaining the old behaviour, unless we were 
> to use "mission.txt" then "mission-1.txt".

I think that's a reasonable change to preserve backwards compatibility.

>   - it would be awesome if we could take a mavlink log and extract both the 
> mission and the course flown, and pack it into the one KML file.  We have 
> the "mavkml.py" script which extracts flight paths but not missions. 
> Perhaps it would be better to have the functionality added to mavkml 
> rather than mavmission.py (which is usually used to extract a mission in a 
> form that can then be uploaded to a vehicle)?

Sounds like we should really have a merger of `mavmission` and `mavkml`, as they have some similar featuresets. Maybe `mavextract`? It'd effectively be a superset, so you could call it like the following:

  * `mavextract MYLOG.mavlink --missions --output=mission-%d.txt`
  * `mavextract MYLOG.mavlink --position --output=course.kml

Then this PR can be dropped and there're no backwards-compatibility requirements, which is very nice.

**Comment by Susurrus** [comment]
Closing this as there's been no movement on it for a couple of years now.

**Pull request closed without merging**
