### PR TITLE
adding bitmask="true" for enums

### PR DESCRIPTION
**Pull request by BazookaJoe1900**
this can help decoders to decide to look for exact value, or mix of bits

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @BazookaJoe1900 , but this will break the schema checks: https://mavlink.io/en/guide/xml_schema.html

The bitmask is declared when the enum is **used**. That makes sense because that is the point the user of the API is creating a UI - which is where QGC at least uses the information.
If you think this adds value over or in addition to having it at that point (and I can see arguments for that) then you would need to update the schema doc first to support this.

Thoughts?

**Comment by BazookaJoe1900** [comment]
@hamishwillee, Yes I see value of this metadata. and I understand its break the current schema.
Basically every data that the XML can give, as soon as possible is better, then in later stages. I look at the XML as source code, of course that later it being translated to different languages (C, C++, C#, LUA). there is no need to spread the metadata on the ground-station (and tell on the GCS that thas bitmast is bit-field, and other is not)

**Comment by hamishwillee** [comment]
@DonLakeFlyer The proposal here is to move the enum "this is a bitmask" information to the bitmask, as well as/possibly instead of the place where the enum is used.

As the GCS is the main consumer of this information, does it make any/much difference to you?

```
<enum name="HL_FAILURE_FLAG" bitmask="true">
```

FWIW I actually like this idea from an information management point of view. But not sure of the cost to existing consumers.

**Comment by DonLakeFlyer** [comment]
Change makes sense. Also just FYI: At this point QGC does not currently use this information.

**Comment by hamishwillee** [comment]
> Change makes sense. Also just FYI: At this point QGC does not currently use this information.

Thanks @DonLakeFlyer . I thought you used it to render enums as checkboxes. Learn something new every day :-)

**Comment by hamishwillee** [comment]
@BazookaJoe1900 OK, since Don is good with this, can you please create a PR in https://github.com/ArduPilot/pymavlink/blob/master/generator/mavschema.xsd to allow this syntax and then cross link to here (since this can't go in until that merges). We'll remove the `display="bitmask"` as a later pass.

**Comment by DonLakeFlyer** [comment]
> I thought you used it to render enums as checkboxes. Learn something new every day :-)

QGC has had it's own internal system for meta data on commands prior to any of this existing in mavlink. The majority of these mavlink changes mirror stuff which already exists in QGC in that internal system. At some point it will switch to using the mavlink data, but right now that's not at the top of the list to get done.

**Comment by amilcarlucas** [comment]
I stll do not get why is this better than the existing display=bitmask

**Comment by hamishwillee** [comment]
@amilcarlucas  If the enum is tagged as representing a bitmap then this approach ensures that this gets reflected wherever the enum is used. Essentially that is less prone to error (and less verbose) than choosing to tag wherever the bitmap is used.

**Comment by DonLakeFlyer** [comment]
As I said above I don't currently use any of this in QGC. At some point in the future I will.

**Comment by BazookaJoe1900** [comment]
Its sound to me like it ok to go with the change

**Comment by hamishwillee** [comment]
@amilcarlucas @peterbarker Can you please merge then.

**Comment by peterbarker** [comment]
Appears to require a rebase here.

**Comment by BazookaJoe1900** [comment]
rebased

**Comment by peterbarker** [comment]
On Wed, 25 Mar 2020, BazookaJoe1900 wrote:

> rebased

Thanks.

The pymavlink PR's been merged now, so you should be able to get this to 
pass CI now.

... might require someone with mavlink-repo privileges to push the retry 
button.

**Comment by hamishwillee** [comment]
I'm confused @peterbarker - this  says isn't merged. Once it is, I could pull it upstream.

**Comment by peterbarker** [comment]
@hamishwillee 

The pymavlink PR referenced on this PR has been merged.  Was there another you were thinking of?

image

**Comment by hamishwillee** [comment]
@peterbarker I am an idiot. Ignore me. I will submit PR to update Pymavlink so this can merge.

**Comment by hamishwillee** [comment]
Merged. Thanks @BazookaJoe1900 !

**Comment by hamishwillee** [comment]
Next step - to remove the values from fields :-)

**Pull request merged**
