### PR TITLE
[WIP] mavlink: Single instance of SHA and CRC save 9640 bytes of flash

### PR DESCRIPTION
**Pull request by dagar**
WIP while I figure out the proper pymavlink solution.

@davids5

https://github.com/PX4/Firmware/pull/9970
https://github.com/mavlink/c_library_v2/commit/9b3d6b2b62bf9b4c727d8d84ef507a8dcd0995f1
https://github.com/mavlink/c_library_v2/pull/2

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Build fail.

**Comment by dagar** [comment]
It's the previous update (https://github.com/mavlink/mavlink/pull/962), not that this should be merged yet.

**Comment by amilcarlucas** [comment]
Please rebase on mavlink master

**Comment by hamishwillee** [comment]
@dagar Can this be closed? If not, can we have an update on state/what this is waiting on?

**Comment by dagar** [comment]
Yes, we found a solution firmware side. Handling it in mavlink itself requires a somewhat awkward juggling of the build.

**Pull request closed without merging**
