### PR TITLE
adsb_vehicle: add squawk flag, convert floats to ints

### PR DESCRIPTION
**Pull request by magicrub**
Changes:
1) Add a Squawk validity flag.  It is not entirely clear if a squawk value of 0 is invalid per https://en.wikipedia.org/wiki/Transponder_(aeronautics) so use a new validity flag.
2) change altitude from float to int32 and it's unit from meters to mm
3) change hor velocity from float to uint16 and it's unit from m/s to cm/s
4) change vert velocity from float to uint16 and it's unit from m/s to cm/s
5) change index of simulated flag from bit 32 to 64

### CODE REVIEW

**Comment by tridge** [comment]
Hi Tom,
The change from m/s to cm/s means we can't provide information on vehicles that travel at over 655m/s. I think there are already vehicles in the world with transponders on-board that can fly faster than that (eg. Blackbird). I know they are rare now, but this packet will be with us for a long time, and it seems silly to save the bytes now and risk not being able to avoid future fast moving aircraft.
I'm also not sure why avoiding floats here matters? Even 8 bit AVR CPUs handle floats fine for this sort of thing.
This MAVLink packet is meant to be for all ADSB devices in the future, so we need to think about broad usage (without going silly).
Cheers, Tridge

**Comment by magicrub** [comment]
I am in agreement with you. Even though mach 2 is extremely fast, there's no good reason to set that as the limit on a new standard packet. Using decimeters (1E^-1) is also silly. Personally, I would prefer changed items 2,3,4 be reverted back to float m/s. This is a request by the vendor. If there is no compelling reason to change it then I would discourage those changes.

**Comment by magicrub** [comment]
I don't mind if the velocities are uint32 in cm/s but agree that uint16 is not quite good enough. We really need uint17!

**Comment by magicrub** [comment]
I talked to Jeff from uAvionix and explained things:
- ADSB velocity data is transmitted as 10bits in knots. So that's 0 - 526m/s. Therefore 0 - 65535 cm/s is appropriate because it is limited by the ADS-B protocol. There's a provision for super-sonic but can not be tested.
- ADSB altitude data is transmitted as 11 bits in 25ft increments with a 1000ft negative offset. That offers a range of -1000 ft to 50175 ft. This warrants >16 for a signed variable with meters accuracy. Therefore 32bits is required. Question is which one? Float m, int32 cm, or int32 mm?

**Comment by magicrub** [comment]
Let me sum up the altitude field:
- Tridge and I my favor altitude in float/m or int32/cm
- Hardware vendor was using float/m then proposed changing to int32/mm.

There is no resolution advantage using any of the three since ADS-B obliterates it to 8.3m per-bit resolution over-the-air via 12bit field. Also, since there are no other floats in the field we might as well use cm/mm instead of float since resolution and range are no longer a limitation.

Altitude Pro/Cons for cm:
- Pro: range is +/- 214 Km

Altitude Pro/Cons for mm:
- Pro: range is +/- 2147 Km
- Con: Height/Altitude in mm is a new unit that we would prefer not to introduce in order to reduce human error when programming.

**Comment by LorenzMeier** [comment]
At that point I'm fine with either. Please use whatever seems more suitable / consistent - sounds like cm?

**Comment by magicrub** [comment]
@LorenzMeier Hardware vendor wants mm, Tridge is not in favor of it but it's not the end of the world if it gets pushed through.

**Comment by magicrub** [comment]
**NOTE** the value of MAV_COMP_ID_ADSB was just bumped to 156 due to another old PR that just got merged in while we were discussing this.

**Comment by magicrub** [comment]
Hardware vendor *really* wants altitude in mm so this PR is good as-is. Please merge and update pymavlink

**Comment by magicrub** [comment]
ArduPilot PR: https://github.com/diydrones/ardupilot/pull/3309

**Pull request merged**
