### PR TITLE
This adds MAVLink2 support and removes MAVLink 0.9 support

### PR DESCRIPTION
**Pull request by tridge**
See this document for details:
https://github.com/ArduPilot/mavlink/blob/mavlink2-wip/doc/MAVLink2.md

### CODE REVIEW

**Comment by tridge** [comment]
See this PR for the matching patches in ArduPilot to support MAVLink2, signing and automatic protocol detection:
https://github.com/ArduPilot/ardupilot/pull/3859

**Comment by vooon** [comment]
@tridge could you please add `void * user_data` for `mavlink_accept_unsigned_t`?

Maybe into `mavlink_status_t`?

**Comment by tridge** [comment]
@vooon, the callback already has the status pointer which can be used to match up to a data structure in the caller. A void * is both not type safe and also isn't enough to do C++ functors properly.
If there is a need for more context then I'd far rather add a field into mavlink_status_t. That is the only place the void* in the callback could come from anyway.
I'd want to understand what the need is for that void* is though.

**Comment by tridge** [comment]
Please see this link for the detailed design of the signing protocol:
https://docs.google.com/document/d/1ETle6qQRcaNWAmpG2wz0oOpFKSF_bcTmYMQvtTGI8ns/edit?usp=sharing

**Comment by vooon** [comment]
I think that common way to hook C callback to C++ class is via wrapper:
```cpp
extern "C" void callback_wrapper(void *user /* args... */) {
    auto p = dynamic_cast<MyClass *>(user);
    p->callback(/* args... */);
}
```

**Comment by vooon** [comment]
Oh, and obvious things: sha256 and sign looks not endianness safe; headless pack not implemented (w/o finalize), but mentioned.

**Comment by tridge** [comment]
@vooon, yes, its a common method, but not actually portable. To make it portable needs a bit more stuff (and more storage space than a single pointer). 
The sha256 code could certainly be improved to make it more portable.
headerless pack is a bit tricky as the pack can now depend on the protocol options (ie. if you have any extensions in the packet). Do you have a specific use case in mind?

**Comment by vooon** [comment]
> Do you have a specific use case in mind?

Not, just that may help with sequence numbers when multiple threads generate messages.
I.e. `producer thread -msg-> queue -msg-> comm thread (finalize; byte buffer) -bytes-> comm channel`.

**Comment by tridge** [comment]
I just wanted to note that in my testing of MAVLink2 the biggest issue I have found is problems with the support for MAVLink2 in the SiK radio firmware. I have a set of patches for the SiK firmware, but it isn't stable yet.

**Comment by LorenzMeier** [comment]
Can you rebase this on master? I'd like to get it in now.

**Comment by tridge** [comment]
I have rebased and added your commits, plus added a new set of commits to allow auto-generation of the information needed to do routing (ie. the target_system offset and target_component offset).
See this code for an example of how that can be used:
https://github.com/ArduPilot/ardupilot/blob/pr-mavlink2/libraries/GCS_MAVLink/MAVLink_routing.cpp#L305

**Comment by LorenzMeier** [comment]
Nice! I've merged this now to master. Now on to deploy this!

**Comment by magicrub** [comment]
Woo hoo!

**Pull request merged**
