### PR TITLE
HOME_POSITION - clarify local frame means NED

### PR DESCRIPTION
**Pull request by hamishwillee**
Removes ambiguity on direction of HOME_POSITION frame. 

@tridge @julianoes OK?

### CODE REVIEW

**Review by julianoes — APPROVED** [review]
This describes the status quo for PX4, so I would say that's correct from that side.

**Comment by julianoes** [comment]
It looks like ArduPilot just sets it to all 0: https://github.com/ArduPilot/ardupilot/blob/0c73da5e79e7c8fe91535d95e4f38dab5120a3c3/libraries/GCS_MAVLink/GCS_Common.cpp#L2584

**Comment by hamishwillee** [comment]
Yeah, I think they are implementing it now, and want to make sure that it matches.

**Comment by mustafa-gokce** [comment]
@hamishwillee, @julianoes with https://github.com/ArduPilot/ardupilot/pull/21642, we will also send local position in NED frame in HOME_POSITION message.
Thanks.

**Review by tridge — APPROVED** [review]

**Comment by hamishwillee** [comment]
Excellent! Thanks @mustafa-gokce

**Pull request merged**
