### PR TITLE
Fix typo in explanation of vz

### PR DESCRIPTION
**Pull request by h4writer**
The description of GLOBAL_POSITION_INT mentions the following: "The position is in GPS-frame (right-handed, Z-up)". Now the explanation used for vz is saying "Ground Z Speed (Altitude, positive down), expressed as m/s * 100". One of the two is fault. The simulator is giving Z-up. I.e. the vz description is fault.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Any progress on this ? is this true ?

**Comment by amilcarlucas** [comment]
Was this tested with ardupilot ? There was a similar bug that got fixed recently in ardupilot master.
Can you retest with the latest master ?

**Comment by amilcarlucas** [comment]
Seven months later, still no reply ... and now it needs a rebase.

**Comment by hamishwillee** [comment]
This seems correct to me (it is possible but not sensible that the position and velocity might define the direction of Z differently). @amilcarlucas What is this waiting on - just someone to approve it?

**Comment by amilcarlucas** [comment]
Yes, this just needs someone to confirm it and approve it

**Comment by julianoes** [comment]
Thanks @h4writer.

**Comment by amilcarlucas** [comment]
I messed up. I failed to ask around in the Ardupilot team. Basically it breaks the ardupilot code and a lot of ground stations. So the Ardupilot team opposes to this change.

Can this please be reverted ?

**Comment by h4writer** [comment]
I don't get this sentiment? Why would it break the ardupilot code?
This is only a change in text. It corrects the text to say what it actually does, instead of saying something bogus.

**Comment by amilcarlucas** [comment]
Because the ardupilot honors that comment and points down (NED).

By just changing the comment to NEU, you effectively break the code.

**Comment by julianoes** [comment]
Well, I did not review this correctly. Everything in PX4 is NED as far as I know and I completely misread this diff.

**Comment by WickedShell** [comment]
Yeah, my brief investigation shows that PX4 was sending NED before (I didn't spend long enough to find the structure definition in current PX4 master). Can we agree that this was the wrong change and sending NED is correct and fix the top level description to be consistent? (Since all major projects/GCS's are expecting the previous behavior I think that makes more sense).

**Comment by mhkabir** [comment]
@WickedShell is correct. The field definition was fine before. The wrong part was the description of the message ("The position is in GPS-frame (right-handed, Z-up)").

**Comment by julianoes** [comment]
> Can we agree that this was the wrong change and sending NED is correct and fix the top level description to be consistent?

Yes, I agree!

**Comment by amilcarlucas** [comment]
Just hold a second, I need to get some input from @rmackay9 on this thing. I hope we can clarify this in the next few days.

**Comment by julianoes** [comment]
Here is the PR to undo this: #892

**Comment by julianoes** [comment]
> And PX4 was also using NED up until this commit 23 days ago: PX4/Firmware@deb5cbc

I don't think it was changed in there @amilcarlucas.

**Comment by amilcarlucas** [comment]
ardupilot/ardupilot#8192 explains the ardupilot side of things. But I still need the feedback from @rmackay9 on this. I was at the meeting where that commit was discussed and approved. I know the background for the decision. But the final word comes from Randy. I hope he replies in the next few days.

**Pull request merged**
