### PR TITLE
common: add FOCUS_TYPE_AUTO

### PR DESCRIPTION
**Pull request by dayjaby**
The current SET_FOCUS_TYPEs are mainly useful for controlling the camera focus via remote control (FOCUS_TYPE_STEP or FOCUS_TYPE_CONTINUOUS) or for specific control of the focus (FOCUS_TYPE_METERS). With this PR we are adding some auto focus types, which most of the modern cameras have:

- FOCUS_TYPE_AUTO: Full automatic focus
- FOCUS_TYPE_SINGLE (aka AF-S): Good for still pictures
- FOCUS_TYPE_CONTINUOUS (aka AF-C): Good for dynamic scenes

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
What's the difference between AUTO and the other auto modes?

@julianoes This looks sensible to me, but you're more familiar with camera stuff.

**Comment by dayjaby** [comment]
AUTO lets the camera decide on its own whether to do AF-C or AF-S. There seem to be a lot of other modes out there (see for example https://youtu.be/JHKXec-Kfrg?t=72), but these ones work best for me on a Sony UMC-R10C.

**Review by julianoes — APPROVED** [review]
Makes sense.

**Comment by hamishwillee** [comment]
@auturgy FYI. Merging as these are consistent.

**Comment by hamishwillee** [comment]
Thanks @dayjaby !

**Pull request merged**
