### PR TITLE
Added MAV_CMD_NAV_ALTITUDE_WAIT to common.xml

### PR DESCRIPTION
**Pull request by JGSOpenSrc**
Define was missing from common.xml but was in ardupilotmega.xml, causing issues compiling qgroundcontrol.

### CODE REVIEW

**Comment by JGSOpenSrc** [comment]
I apologize if this seems off. I'm new to git.

My intent was only to add MAV_CMD_NAV_ALTITUDE_WAIT to common.xml, I'm not sure what the changes are to mavgen_python.py or how they got there.. Those changes didn't show up when I ran git diff on my local repository.

**Comment by LorenzMeier** [comment]
You would need to strip it from the Ardupilot XML as well to make this work. @tridge @rmackay9 Are you ok to pull this into common to solve some of the cross-stack issues

**Comment by rmackay9** [comment]
I had a peek but it's only used in Plane so it's a question more for @tridge and/or @magicrub.  As a side note, I don't see any MAV_CMD conflict (it's 83) so I'm not sure why this would cause compile issues.

**Comment by JGSOpenSrc** [comment]
The absence of this command definition breaks compilation of QGroundControl when it is built for a mavlink dialect that does not contain this command definition.

The project defaults to including ardupilotmega, which does contain this definition.

An alternative would be to correct the problem in the QGroundControl source. I believe the command is referenced in a method in the MissionManager package.

**Comment by magicrub** [comment]
Well I don't have any problems with this going in as long as it's not
breaking the builds (of course).

**Comment by magicrub** [comment]
would be nice to clean up the commit (ie, remove the merge and remove the
whitespace stuff)

**Comment by JGSOpenSrc** [comment]
Magicrub,

To do that, would I close this pull request and open a new one?

**Comment by magicrub** [comment]
@JGSOpenSrc you commit and push to this branch, github magically updates the PR

**Comment by magicrub** [comment]
Hi @JGSOpenSrc 
Seems you just pushed 20 commits for these 2 files. I see many merges - ouch. You must have quite a mess going on over there! What tool are you using to do git stuff? if you'r eon Windows or Mac I'd suggest sourcetree.

**Comment by LorenzMeier** [comment]
Closing as stale. Please re-open a rebased PR otherwise.

**Pull request closed without merging**
