### PR TITLE
add HIL_ACTUATOR_CONTROLS

### PR DESCRIPTION
**Pull request by bkueng**
This is a replacement for HIL_CONTROLS, with 16 channels instead of only 8.

@LorenzMeier can you review this please?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@julianoes Any thoughts what might be missing?

**Comment by bkueng** [comment]
One thing I was considering adding was an integer number_of_outputs that are actually set. Not sure if that could become useful.

**Comment by julianoes** [comment]
> One thing I was considering adding was an integer number_of_outputs that are actually set. Not sure if that could become useful.

Oh I agree, good point.

**Comment by vooon** [comment]
> number_of_outputs

You can use NAN as unset state.

**Comment by LorenzMeier** [comment]
So what I'll do is add a 64bit field for flags and reserve it.

**Comment by bkueng** [comment]
ok sure. And remove one of the modes?

**Comment by LorenzMeier** [comment]
Rebased, adjusted and pushed. Flags added and nav mode dropped.

**Comment by bkueng** [comment]
Thanks!

**Pull request closed without merging**
