### PR TITLE
add ftp.xml containing enums for ftp service

### PR DESCRIPTION
**Pull request by muexxl**
Hi all, 
I added the enums for the ftp service in a seprate XML file according to https://mavlink.io/en/services/ftp.html
This is my first attempt to contribute. not sure if this is how its being done. 
//Muexxl

### CODE REVIEW

**Comment by peterbarker** [comment]
Why the separate file?  I think by convention we'd lump everything together.

I know @hamishwillee has been thinking about trying to separate things a bit, but it should probably be all-or-nothing, not half-here-half-there for logically collected things like ftp messages and their enumerations.

**Comment by hamishwillee** [comment]
Thanks @muexxl.
As @peterbarker says, IF we want to do this, we should put this into common.xml. I do want to make the protocols more modular, but have not had broad agreement.

But I do not want to do this now. The benefit of enums in MAVLink is that they document and enforce allowed values. However the [FILE_TRANSFER_PROTOCOL](https://mavlink.io/en/messages/common.html#FILE_TRANSFER_PROTOCOL) is an opaque field. So there is no way to link these enums to the message, and hence IMO not worth it.

What would be good is to design a replacement message/service that does this right.
The simple approach would be one that just redefines the fields currently defined as being in the payload into the message itself. That would allow enforcement of the structure, and easy packing and unpacking. 
If we were going to do that, we'd also take the time to think about whether this might be further improved by breaking it down into several messages. 

@peterbarker Do you think there is any interest ArduPilot side in improving the message?

**Comment by hamishwillee** [comment]
PS, closing because we can't accept this. Thanks again @muexxl .

**Comment by peterbarker** [comment]
[10:03 AM] Peter Barker: @Muexxl while @Hamish Willee did close that initial pull request, I would actually like to see us get rid of those magic numbers somehow.  If we were to move to an FTP message which was less convoluted any such enumeration should be able to be re-used, so I'm really not sure why we couldn't create it now.  Even if we were not to add it to the mavlink standard, even having an internal ArduPilot enumeration in place of the damned fixed numbers would be nice!  Having them in the standards document would at least make people implementing or adjusting the standard consider what it might mean for other implementors!  Cross-posting this back to the closed PR, too 🙂

(cross-posted from ArduPilot's Discord pymavlink channel)

**Comment by hamishwillee** [comment]
FYI only, the general feeling in the dev call was that there is value in the current message design. Specifically that it mirrors the official FTP spec data structure and sequences in mavlink. So we probably won't change it. I added a note in https://mavlink.io/en/services/ftp.html to capture this:
image

That said, I would not personally be opposed to having an enum instead of the magic numbers if that would help developers. Someone else would have to put that in common.xml. Whether or not it went in would then depend on all stakeholders to the standard, but I expect it would be accepted.

**Pull request closed without merging**
