### PR TITLE
Add instance=true to some messages

### PR DESCRIPTION
**Pull request by olliw42**
I think this is what the instance attribute is for, adds it to some more messages, especially the gimbal v2 messages.

There might be few more places there this should have been added; I've done it just where I was kind of sure it's what it should be :)

### CODE REVIEW

**Comment by hamishwillee** [comment]
@olliw42 Thanks very much. 

The `instance="true"` indicates that the message can contain from a number of sources (e.g. a sensor), and identifies the field that can be used to differentiate those sources. This allows the information from two sensors to be carried in the same message in separate calls, and the recipient to be able to group the messages for each sensor together.

I think that this works provided each message carries just the data for one sensor. This therefore will work for batteries, optical flow, gimbal etc. However I don't think that it will work for ESC_INFO etc, where the index is not the identify of a single ESC, but rather the index into an array containing data for multiple ESC.
Thoughts?

@amilcarlucas I would appreciate your review.

**Comment by olliw42** [comment]
yeah, I was thinking about the ESC case. I concluded however that, for a given setup, each index into the array is tautologous to the id of the esc, i.e. the data of one esc will always end up in exactly the same array index ... so, if one wanted to plot the data of one esc one would need exactly this value ... 

> The instance="true" indicates that the message can contain from a number of sources (e.g. a sensor), and identifies the field that can be used to differentiate those sources. This allows the information from two sensors to be carried in the same message in separate calls, and the recipient to be able to group the messages for each sensor together.

I am not sure this is what the the attribute is for, my understanding is slightly different. At the code level of digesting a message the recipient can differentiate the different sources by the mere fact that there is an id field, without any need of any attribute. In my understanding the attribute is pure metadata which e.g. allows plotting tools to automatically produce instance specific plots.

**Comment by hamishwillee** [comment]
> recipient can differentiate the different sources by the mere fact that there is an id field

I'm not sure the distinction you're trying to draw, but the id field doesn't have to be called id.

@amilcarlucas Can you please check the ESC_INFO fields that @olliw42 has marked up and convince yourself that these would work properly? I *think* it probably works for the reasons Ollie says.

**Review by amilcarlucas — APPROVED** [review]
yes, you nailed it.

**Comment by hamishwillee** [comment]
Thanks @olliw42 @amilcarlucas!

**Pull request merged**
