### PR TITLE
Common: Allow CMD_DO_LAND_START to change the flight mode

### PR DESCRIPTION
**Pull request by WickedShell**
Useful for simplifying the number of commands and state machine used to safely transition a vehicle to flying a landing sequence. An example use case would be changing the flight mode to AUTO for ArduPlane.

### CODE REVIEW

**Comment by magicrub** [comment]
I don't understand what you're​ trying to do here

**Comment by DonLakeFlyer** [comment]
My take on this one is that if the vehicle needs to go into a specific flight mode to execute this command then it should just do it. If this is inappropriate at the time, then it just fails. Seems simpler.

**Comment by WickedShell** [comment]
@magicrub If I want to jump to a landing start right now I need to:

1. Send MAV_CMD_DO_LAND_START
2. Wait for an ACK/NACK and retry till I get it
3. Send a mode change
4. Wait for an ACK/NACK/mode change

The problem with this is it makes it take much longer to achieve the desired behavior in a poor telemetry situation, and as @DonLakeFlyer said, I've asked the vehicle to prep to fly a landing, I should be able to just instruct it to fly a landing in one pass.

**Comment by magicrub** [comment]
So this is not the mission item version?

**Comment by WickedShell** [comment]
This is the same command you plan in a mission, however a mission would ignore the param1 field (as it's obviously already in the correct mode if it's executing it), but when sent as a COMMAND_LONG you would evaluate the param1 field as a mode change request.

**Comment by magicrub** [comment]
We had talked about a configure land mission cmd, but that was for auto flight. Could the same type of new command be used instead of modifying this one?

**Comment by WickedShell** [comment]
Configure landing was discussed in the context of keepouts/approaches. It was never discussed as a way to start the sequence. Given that this is the existing preferred method to setup a mission for actually being a landing, I'd rather stick with it as the interface for doing so, rather then having two different interfaces that overlap in functionality.

**Comment by dagar** [comment]
Is the behaviour of sending MAV_CMD_DO_LAND_START without a mode change actually desired?

**Comment by WickedShell** [comment]
It can be useful to prep a mission before you actually want to fly it, so I'd say there is merit to not always forcing the mode change.

**Comment by DonLakeFlyer** [comment]
> It can be useful to prep a mission before you actually want to fly it, so I'd say there is merit to not always forcing the mode change.

I don't get that. Can you explain how that would be used?

**Comment by WickedShell** [comment]
@DonLakeFlyer It's a really rare scenario. I've normally performed this with just set-wp commands, and while the aircraft was in guided (or being flown manually) I've tweaked the target mission waypoint, and then waited until the aircraft was aligned with the flight path before swapping back to auto. I'm happy to let go of this use case, but I thought it was more valuable to have the flexibility.

**Comment by LorenzMeier** [comment]
@WickedShell Based on the discussion here: Is this really needed or not? If possible we should avoid complex special cases and keep the execution of a mission as linear and standard as possible.

**Comment by LorenzMeier** [comment]
Closing as stale - please re-open a new rebased PR if this is still needed.

**Pull request closed without merging**
