### PR TITLE
Stevsics

### PR DESCRIPTION
**Pull request by stevsics**
New message type added for sending commands to FMU.

### CODE REVIEW

**Comment by TSC21** [comment]
@stevsics I can't seem to understand why you need this when you have `SET_POSITION_TARGET_LOCAL_NED`.

**Comment by stevsics** [comment]
The message is much shorter. If used in applications where time is critical, apparently SET_POSITION_TARGET_LOCAL_NED can cause problems. Also, it is easier to understand. SET_POSITION_TARGET_LOCAL_NED gives opportunity to send position, velocity and acceleration setpoints at the same time which doesn't make much sense. I had discussion with Lorenz about this, he agreed that this can be useful.

**Comment by TSC21** [comment]
> If used in applications where time is critical, apparently SET_POSITION_TARGET_LOCAL_NED can cause problems

Didn't heard about problems related to this.

> SET_POSITION_TARGET_LOCAL_NED gives opportunity to send position, velocity and acceleration setpoints at the same time

That's why you use a bitmask. And that allows you to don't have to depend on external enumerations for the same purpose.

**Comment by stevsics** [comment]
Well, I talked with a guy from my group, he had exactly this problem when he tried to have offboard control from a desktop PC. Messages were sent over LairdTech module. He implemented a new shorter message type and this solved the problem, but he never did a pull request.

As you wish, this is just another feature that solves sending of offboard setpoints in more elegant way. For me it works perfectly well:)

**Comment by TSC21** [comment]
Well, saying it works is a thing, showing it is always better. Logs and videos comparing both implementations are welcomed. Cause having two msgs to do the same doesn't seem to be the best approach.

**Pull request closed without merging**
